(function(){
  const c=()=>window.SYKA_SUPABASE.get();
  const q=async(table,select='*',opts={})=>{let query=c().from(table).select(select);if(opts.eq)Object.entries(opts.eq).forEach(([k,v])=>query=query.eq(k,v));if(opts.order)query=query.order(opts.order,{ascending:opts.ascending!==false});if(opts.limit)query=query.limit(opts.limit);const{data,error}=await query;if(error)throw error;return data||[];};
  async function listUsers({search='',limit=100}={}){let query=c().from('profiles').select('id,username,full_name,grade,institution,avatar_url,status,created_at,updated_at').order('created_at',{ascending:false}).limit(limit);if(search.trim())query=query.or(`username.ilike.%${search.trim()}%,full_name.ilike.%${search.trim()}%,institution.ilike.%${search.trim()}%`);const{data,error}=await query;if(error)throw error;if(!data?.length)return[];const ids=data.map(x=>x.id);const{data:roles,error:re}=await c().from('user_roles').select('user_id,role,is_active').in('user_id',ids);if(re)throw re;const map={};(roles||[]).forEach(r=>(map[r.user_id]??=[]).push(r));return data.map(p=>({...p,roles:map[p.id]||[]}));}
  async function setUserStatus(id,status,reason){const{data,error}=await c().rpc('admin_set_user_status',{p_user_id:id,p_status:status,p_reason:reason||null});if(error)throw error;return data;}
  async function setUserRole(id,role,active=true,reason){const{data,error}=await c().rpc('admin_set_user_role',{p_user_id:id,p_role:role,p_active:active,p_reason:reason||null});if(error)throw error;return data;}
  async function listCompetitionsAdmin({search='',status='',limit=100}={}){let qy=c().from('competitions').select('id,organizer_id,title,slug,category,status,registration_starts_at,registration_ends_at,starts_at,ends_at,announcement_at,poster_url,visibility,created_at').order('created_at',{ascending:false}).limit(limit);if(search.trim())qy=qy.or(`title.ilike.%${search.trim()}%,slug.ilike.%${search.trim()}%`);if(status)qy=qy.eq('status',status);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function transitionCompetition(id,status,reason){const{data,error}=await c().rpc('transition_competition',{p_competition_id:id,p_to_status:status,p_reason:reason||null});if(error)throw error;return data;}
  async function saveCompetition(payload,id=null){const r=id?await c().from('competitions').update(payload).eq('id',id).select('*').single():await c().from('competitions').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listQuestionBanks({organizerId=null}={}){let qy=c().from('question_banks').select('*').order('created_at',{ascending:false});if(organizerId)qy=qy.eq('organizer_id',organizerId);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function saveQuestionBank(payload,id=null){const r=id?await c().from('question_banks').update(payload).eq('id',id).select('*').single():await c().from('question_banks').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listQuestions({competitionId=null,bankId=null}={}){let qy=c().from('questions').select('id,question_bank_id,competition_id,type,prompt,points,required,display_order,status,config,created_at').order('display_order',{ascending:true});if(competitionId)qy=qy.eq('competition_id',competitionId);if(bankId)qy=qy.eq('question_bank_id',bankId);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function saveQuestion(payload,id=null){const r=id?await c().from('questions').update(payload).eq('id',id).select('*').single():await c().from('questions').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listOptions(questionId){return q('question_options','*',{eq:{question_id:questionId},order:'display_order'});}
  async function replaceOptions(questionId,opts){const{error:de}=await c().from('question_options').delete().eq('question_id',questionId);if(de)throw de;if(opts?.length){const{error}=await c().from('question_options').insert(opts.map((o,i)=>({question_id:questionId,label:o.label,value:o.value,is_correct:!!o.is_correct,display_order:i})));if(error)throw error;}}
  async function listRegistrations({competitionId=null,status=''}={}){let qy=c().from('registrations').select('id,competition_id,user_id,status,twibbon_asset_url,social_proof_url,submitted_at,approved_at,rejected_at,rejection_reason,metadata,profiles:user_id(id,username,full_name,grade,institution,avatar_url),competitions:competition_id(id,title)').order('created_at',{ascending:false});if(competitionId)qy=qy.eq('competition_id',competitionId);if(status)qy=qy.eq('status',status);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function reviewRegistration(id,decision,reason){const{data,error}=await c().rpc('review_registration',{p_registration_id:id,p_decision:decision,p_reason:reason||null});if(error)throw error;return data;}
  async function listAttempts({competitionId=null,status=''}={}){let qy=c().from('attempts').select('id,competition_id,participant_id,registration_id,attempt_number,status,started_at,expires_at,submitted_at,finalized_at,score,profiles:participant_id(id,username,full_name,grade,institution),competitions:competition_id(id,title)').order('created_at',{ascending:false});if(competitionId)qy=qy.eq('competition_id',competitionId);if(status)qy=qy.eq('status',status);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function listGradingItems(attemptId){return q('grading_items','*',{eq:{attempt_id:attemptId},order:'created_at'});}
  async function saveGrade(payload,id=null){const r=id?await c().from('grading_items').update(payload).eq('id',id).select('*').single():await c().from('grading_items').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function finalizeAttempt(attemptId,score){const{data,error}=await c().from('attempts').update({score:Number(score)||0,status:'FINALIZED',finalized_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',attemptId).select('*').single();if(error)throw error;return data;}
  async function listAwards({competitionId=null}={}){let qy=c().from('awards').select('id,user_id,competition_id,rank_code,title,points,emblem_url,issued_at,visibility,profiles:user_id(full_name,username),competitions:competition_id(title)').order('issued_at',{ascending:false});if(competitionId)qy=qy.eq('competition_id',competitionId);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function listCertificates({competitionId=null,status=''}={}){let qy=c().from('certificates').select('id,user_id,competition_id,status,current_revision,created_at,updated_at,profiles:user_id(full_name,username),competitions:competition_id(title)').order('created_at',{ascending:false});if(competitionId)qy=qy.eq('competition_id',competitionId);if(status)qy=qy.eq('status',status);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function updateCertificate(id,status){const{data,error}=await c().from('certificates').update({status,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;}
  async function listOrders({status=''}={}){let qy=c().from('orders').select('id,user_id,status,subtotal,discount,shipping_cost,total,currency,created_at,updated_at,profiles:user_id(full_name,username)').order('created_at',{ascending:false});if(status)qy=qy.eq('status',status);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function updateOrder(id,status){const{data,error}=await c().from('orders').update({status,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;}

  async function listLevels(competitionId){return q('competition_levels','*',{eq:{competition_id:competitionId},order:'created_at'});}
  async function saveLevel(payload,id=null){const r=id?await c().from('competition_levels').update(payload).eq('id',id).select('*').single():await c().from('competition_levels').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function getRegistrationRules(competitionId){const{data,error}=await c().from('registration_rules').select('*').eq('competition_id',competitionId).maybeSingle();if(error)throw error;return data;}
  async function saveRegistrationRules(payload,competitionId){const r=await c().from('registration_rules').upsert({...payload,competition_id:competitionId},{onConflict:'competition_id'}).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listRewards(competitionId){return q('competition_rewards','*',{eq:{competition_id:competitionId},order:'created_at'});}
  async function saveReward(payload,id=null){const r=id?await c().from('competition_rewards').update(payload).eq('id',id).select('*').single():await c().from('competition_rewards').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function createCertificate(payload){const{data,error}=await c().from('certificates').insert(payload).select('*').single();if(error)throw error;return data;}
  async function moderateQuestion(id,status){const{data,error}=await c().from('questions').update({status,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;}
  async function listTwibbonTemplates({competitionId=null,organizerId=null}={}){let qy=c().from('twibbon_templates').select('*').order('created_at',{ascending:false});if(competitionId)qy=qy.eq('competition_id',competitionId);if(organizerId)qy=qy.eq('organizer_id',organizerId);const{data,error}=await qy;if(error)throw error;return data||[];}
  async function saveTwibbonTemplate(payload,id=null){const r=id?await c().from('twibbon_templates').update(payload).eq('id',id).select('*').single():await c().from('twibbon_templates').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listModeration(){const[{data:posts,error:pe},{data:comments,error:ce},{data:reports,error:re}]=await Promise.all([c().from('posts').select('id,title,status,created_at,author_user_id').order('created_at',{ascending:false}).limit(50),c().from('comments').select('id,body,moderation_state,created_at,user_id').order('created_at',{ascending:false}).limit(50),c().from('comment_reports').select('id,comment_id,reason,status,created_at').order('created_at',{ascending:false}).limit(50)]);if(pe)throw pe;if(ce)throw ce;if(re)throw re;return{posts:posts||[],comments:comments||[],reports:reports||[]};}
  async function moderatePost(id,status){const{data,error}=await c().from('posts').update({status,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;}
  async function moderateComment(id,state){const{data,error}=await c().from('comments').update({moderation_state:state,updated_at:new Date().toISOString()}).eq('id',id).select('*').single();if(error)throw error;return data;}
  async function listPlans(){return q('organizer_plans','*',{order:'created_at',ascending:false});}
  async function listEntitlements(){return q('plan_entitlements','*',{order:'plan_code'});}
  async function saveEntitlement(payload,id=null){const r=id?await c().from('plan_entitlements').update(payload).eq('id',id).select('*').single():await c().from('plan_entitlements').insert(payload).select('*').single();if(r.error)throw r.error;return r.data;}
  async function listFlags(){return q('feature_flags','*',{order:'key'});}
  async function setFlag(key,enabled,config={}){const{data,error}=await c().from('feature_flags').upsert({key,enabled,config,updated_at:new Date().toISOString()},{onConflict:'key'}).select('*').single();if(error)throw error;return data;}
  async function listSettings(){return q('global_settings','*',{order:'key'});}
  async function setSetting(key,value){const{data,error}=await c().from('global_settings').upsert({key,value,updated_at:new Date().toISOString()},{onConflict:'key'}).select('*').single();if(error)throw error;return data;}
  async function listAudit({limit=100,action=''}={}){let qy=c().from('audit_logs').select('*').order('created_at',{ascending:false}).limit(limit);if(action)qy=qy.ilike('action',`%${action}%`);const{data,error}=await qy;if(error)throw error;return data||[];}
  window.SYKA_CONTROL_SERVICE={q,listUsers,setUserStatus,setUserRole,listCompetitionsAdmin,transitionCompetition,saveCompetition,listLevels,saveLevel,getRegistrationRules,saveRegistrationRules,listRewards,saveReward,createCertificate,listQuestionBanks,saveQuestionBank,listQuestions,saveQuestion,listOptions,replaceOptions,listRegistrations,reviewRegistration,listAttempts,listGradingItems,saveGrade,finalizeAttempt,listAwards,listCertificates,updateCertificate,listOrders,updateOrder,listTwibbonTemplates,saveTwibbonTemplate,listModeration,moderatePost,moderateComment,moderateQuestion,listPlans,listEntitlements,saveEntitlement,listFlags,setFlag,listSettings,setSetting,listAudit};
})();
