/* Sykabelajar V2 production takeover.
 * Landing (/): marketing surface, NO sidebar/right rail/dashboard chrome.
 * App routes: Bolt dashboard shell, using existing Supabase/services.
 */
(function(){
  if(window.__SYKA_V2_TAKEOVER__)return;
  window.__SYKA_V2_TAKEOVER__=true;

  var dummyNames=['Aruna Putra','Mira Cendekia','Bagaskara Wibawa','Larasati Ayu','Dimas Pratama','Naila Zahra'];
  function isLanding(){try{var r=new URLSearchParams(location.search).get('route')||'/';return r==='/'||r===''}catch(e){return true}}
  function fixes(){if(document.getElementById('syka-v2-production-fixes'))return;var s=document.createElement('style');s.id='syka-v2-production-fixes';s.textContent='html.syka-v2-takeover,html.syka-v2-takeover body{margin:0!important;padding:0!important;width:100%!important;min-width:0!important;background:#060b14!important}body.syka-v2-body{overflow-x:hidden!important}body.syka-v2-body>[data-syka-legacy-hidden="true"]{display:none!important}#page-root{display:block!important;width:100%!important;max-width:none!important;margin:0!important;padding:0!important;min-height:100vh!important;box-sizing:border-box!important}#page-root *{box-sizing:border-box!important}.v2-sidebar .v2-nav svg,.v2-sidebar .v2-nav button svg,.v2-sidebar .v2-nav-plain svg{width:20px!important;height:20px!important;min-width:20px!important;max-width:20px!important}.v2-nav button{min-height:40px!important}.v2-main-body{padding:28px 30px!important}.v2-data-empty{padding:22px 12px;color:var(--v2-muted);font-size:12px;text-align:center;border:1px dashed var(--v2-border2);border-radius:12px}.v2-data-empty-wide{grid-column:1/-1}.v2-comp-cover{background-size:cover!important;background-position:center!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-side,.bolt-layout-controlled.bolt-landing-route #page-root .v2-sidebar,.bolt-layout-controlled.bolt-landing-route #page-root .bolt-rail,.bolt-layout-controlled.bolt-landing-route #page-root .v2-rail{display:none!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-wrap{display:block!important;width:100%!important;max-width:100%!important;min-height:100vh!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-main{width:100%!important;max-width:none!important;border:0!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-body{max-width:none!important;padding:0!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-top{display:none!important}.bolt-layout-controlled.bolt-app-route #page-root .bolt-wrap{display:grid!important}@media(max-width:1100px){.v2-shell-grid{grid-template-columns:204px minmax(0,1fr)!important}.v2-rail{display:none!important}}@media(max-width:820px){.v2-shell-grid{display:block!important}.v2-sidebar{display:none!important}.v2-main-body{padding:22px 16px 80px!important}.v2-container{width:calc(100% - 28px)!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-hero{padding-top:26px!important}.bolt-layout-controlled.bolt-landing-route #page-root .bolt-hero-grid{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
  function isolate(){var r=document.getElementById('page-root');if(!r)return;if(r.parentElement!==document.body)document.body.appendChild(r);Array.prototype.forEach.call(document.body.children,function(e){if(e!==r)e.setAttribute('data-syka-legacy-hidden','true')});document.documentElement.classList.add('syka-v2-takeover');document.body.classList.add('syka-v2-body')}
  function hideLegacy(){fixes();isolate();var landing=isLanding();document.documentElement.classList.toggle('bolt-landing-route',landing);document.documentElement.classList.toggle('bolt-app-route',!landing);document.body.classList.toggle('bolt-landing-route',landing);document.body.classList.toggle('bolt-app-route',!landing);document.querySelectorAll('#app-shell > .sidebar,#app-shell > .main-area > .header,#app-shell > .main-area > #blogger-content,#app-shell > .bottom-nav,#mobile-nav-overlay').forEach(function(e){e.style.setProperty('display','none','important')});var r=document.getElementById('page-root');if(r){r.style.setProperty('display','block','important');r.style.setProperty('width','100%','important');r.style.setProperty('max-width','none','important');r.style.setProperty('min-height','100vh','important');r.style.setProperty('margin','0','important');r.style.setProperty('padding','0','important')};document.querySelectorAll('#page-root .bolt-side,#page-root .v2-sidebar,#page-root .bolt-rail,#page-root .v2-rail').forEach(function(e){if(landing)e.style.setProperty('display','none','important');else e.style.removeProperty('display')});document.documentElement.dataset.sykabelajar='v2'}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c]})}
  function rows(data){if(!data.length)return'<div class="v2-data-empty">Belum ada data peringkat.</div>';return data.slice(0,5).map(function(r,i){var n=r.name||r.full_name||r.display_name||r.username||r.profile_name||('Peserta '+(i+1)),p=Number(r.score??r.points??r.xp??r.total_xp??r.total_points??0);return'<div class="v2-board-row"><b>'+(i+1)+'</b><span class="v2-mini-avatar">'+esc(n).slice(0,2).toUpperCase()+'</span><div><strong>'+esc(n)+'</strong><small>'+esc(r.school||r.institution||'Peserta Sykabelajar')+'</small></div><em>'+p.toLocaleString('id-ID')+'</em></div>'}).join('')}
  async function hydrate(){try{var b=document.querySelector('.v2-hero-board'),ls=window.SYKA_LEADERBOARD_SERVICE;if(b&&ls&&ls.get&&!b.dataset.backendHydrated){var d=await ls.get({scope:'global',limit:5});b.innerHTML='<div class="v2-board-title">Papan Peringkat <span>LIVE</span></div>'+rows(d);b.dataset.backendHydrated='1'}}catch(e){console.warn('[Sykabelajar] leaderboard hydration skipped',e)}try{var svc=window.SYKA_COMPETITION_SERVICE,g=document.querySelector('.v2-comp-grid');if(svc&&svc.list&&g&&!g.dataset.backendHydrated){var d2=await svc.list({limit:6,status:'PUBLIC_ONLY'});if(d2.length){g.innerHTML=d2.map(function(c){var bg=c.poster?" style=\"background-image:url('"+esc(c.poster)+"')\"":'';return'<article class="v2-comp-card"><div class="v2-comp-cover"'+bg+'></div><div class="v2-comp-body"><span class="v2-chip">'+esc(c.category||'Kompetisi')+'</span><h3>'+esc(c.title)+'</h3><p>'+esc(c.description||'Ikuti kompetisi dan raih prestasi.')+'</p><div class="v2-comp-meta"><strong>+300 XP</strong><span>Terbuka</span></div></div></article>'}).join('')}else g.innerHTML='<div class="v2-data-empty v2-data-empty-wide">Belum ada kompetisi publik yang tersedia.</div>';g.dataset.backendHydrated='1'}}catch(e){console.warn('[Sykabelajar] competition hydration skipped',e)}document.querySelectorAll('.v2-board-row').forEach(function(r){if(dummyNames.some(function(n){return r.textContent.indexOf(n)>=0}))r.remove()})}
  async function start(){hideLegacy();if(window.SYKA_V2_RUNTIME&&typeof window.SYKA_V2_RUNTIME.start==='function'){try{await window.SYKA_V2_RUNTIME.start();hideLegacy();setTimeout(hydrate,50);setTimeout(hydrate,500);return}catch(e){console.error('[Sykabelajar V2] takeover start failed:',e)}}if(window.SYKA_V2_BOOTSTRAP&&typeof window.SYKA_V2_BOOTSTRAP==='function'){try{await window.SYKA_V2_BOOTSTRAP();hideLegacy();setTimeout(hydrate,100)}catch(e){console.error('[Sykabelajar V2] bootstrap failed:',e)}}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();window.addEventListener('popstate',function(){hideLegacy();setTimeout(hydrate,100)});setInterval(function(){if(document.getElementById('page-root'))hideLegacy()},1000)
}());
