(function(){
  const esc=window.SYKA_UTILS.escapeHtml;
  const fmt=window.SYKA_UTILS.formatDateTime;
  function scheduleCard(label,start,end,icon){return `<div class="timeline-card-v46"><div class="timeline-card-icon">${icon}</div><span>${esc(label)}</span><strong>${esc(start||'Jadwal menyusul')}</strong>${end?`<small>sampai ${esc(end)}</small>`:''}</div>`;}
  function registrationState(status){
    const map={PUBLISHED:{label:'Pendaftaran belum dibuka',detail:'Kompetisi sudah dipublikasikan. Pantau tanggal pendaftaran.'},REGISTRATION_CLOSED:{label:'Pendaftaran ditutup',detail:'Batas pendaftaran sudah berakhir.'},LIVE:{label:'Kompetisi sedang berjalan',detail:'Pendaftaran peserta baru sudah ditutup.'},SUBMISSION_CLOSED:{label:'Pengumpulan sudah ditutup',detail:'Saat ini kompetisi masuk tahap penilaian.'},GRADING:{label:'Sedang dinilai',detail:'Penyelenggara sedang memproses hasil peserta.'},RESULT_PUBLISHED:{label:'Hasil telah diumumkan',detail:'Lihat rekam prestasi dari akun kamu.'},ARCHIVED:{label:'Kompetisi diarsipkan',detail:'Kompetisi ini sudah selesai.'},SUSPENDED:{label:'Kompetisi ditangguhkan',detail:'Pendaftaran sementara tidak tersedia.'},CANCELLED:{label:'Kompetisi dibatalkan',detail:'Pendaftaran tidak tersedia untuk kompetisi ini.'}};
    return map[status]||{label:'Pendaftaran belum tersedia',detail:'Ikuti informasi resmi penyelenggara.'};
  }
  async function render(root,slug){
    root.innerHTML='<div class="page-loading"><div class="loading-spinner"></div><span>Memuat detail kompetisi…</span></div>';
    const c=await window.SYKA_COMPETITION_SERVICE.getBySlug(slug);
    if(!c){root.innerHTML=window.SYKA_EMPTY.render({title:'Kompetisi tidak ditemukan',text:'Slug kompetisi tidak tersedia atau sudah diarsipkan.',actionHtml:`<a class="btn btn-secondary" href="${window.SYKA_ROUTER.href('/lomba')}">Kembali ke katalog</a>`});return;}
    const [levels,rules,rewards]=await Promise.all([window.SYKA_COMPETITION_SERVICE.getLevels(c.id).catch(()=>[]),window.SYKA_COMPETITION_SERVICE.getRules(c.id).catch(()=>null),window.SYKA_COMPETITION_SERVICE.getRewards(c.id).catch(()=>[])]);
    const auth=window.SYKA_STATE.getState().auth;const reg=auth.user?await window.SYKA_REGISTRATION_SERVICE.getStatus(auth.user.id,c.id).catch(()=>null):null;const poster=window.SYKA_UTILS.cloudinaryTransform(c.poster||c.poster_url,{width:1400,height:820,crop:'fill'});const state=registrationState(c.status);
    const canRegister=['REGISTRATION_OPEN'].includes(c.status);
    root.innerHTML=`<div class="competition-breadcrumb"><a href="${window.SYKA_ROUTER.href('/lomba')}">Lomba</a><span>›</span><strong>${esc(c.category||'Kompetisi')}</strong></div>
    <section class="competition-detail-v46 competition-detail-premium">
      <div class="competition-detail-cover">${poster?`<img src="${esc(poster)}" alt="${esc(c.title)}">`:'<div class="competition-cover-empty"><span>✦</span><strong>Poster kompetisi</strong><small>Belum ditambahkan penyelenggara.</small></div>'}<div class="cover-gradient"></div><div class="cover-badges"><span class="status-pill ${window.SYKA_UTILS.statusClass(c.status)}">${esc(c.status)}</span><span class="chip chip-white">${esc(c.category||'Kompetisi')}</span></div></div>
      <div class="competition-detail-main"><div class="eyebrow">SYKABELAJAR COMPETITION</div><h1>${esc(c.title)}</h1><p class="competition-lead">${esc(c.description||c.short_description||'Ikuti kompetisi, selesaikan prosesnya, dan bangun bukti prestasi yang bisa diverifikasi.')}</p>
        <div class="timeline-grid-v46">${scheduleCard('Pendaftaran',fmt(c.registrationStartsAt),c.registrationEndsAt?fmt(c.registrationEndsAt):'', '◷')}${scheduleCard('Kompetisi',fmt(c.startsAt),c.endsAt?fmt(c.endsAt):'', '✦')}${scheduleCard('Pengumuman',fmt(c.announcementAt),'','✓')}</div>
        <div class="competition-actions-v46">${reg?`<div class="registration-state-box"><span class="eyebrow">STATUS PENDAFTARAN</span><strong>${esc(reg.status||'PENDING')}</strong><small>Status berasal dari server.</small></div>`:canRegister?`<a class="btn btn-primary btn-lg" href="${window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(slug)+'/daftar')}">Daftar sekarang <span>→</span></a>`:`<div class="registration-state-box"><strong>${esc(state.label)}</strong><small>${esc(state.detail)}</small></div>`}<button class="btn btn-secondary btn-lg" id="share-competition">Bagikan</button></div>
      </div>
    </section>
    <section class="detail-grid-v46">
      <section class="panel-card detail-panel-v46"><div class="panel-head"><div><span class="eyebrow">ELIGIBILITY</span><h2>Siapa yang bisa ikut?</h2><p>Persyaratan yang diterapkan penyelenggara.</p></div></div><div class="detail-list detail-list-v46">${[['Jenjang / kelas',levels.length?levels.map(x=>esc(x.label||x.grade||'')).filter(Boolean).join(' · '):((rules?.allowed_grades||[]).join(' · ')||'Mengikuti aturan kompetisi')],['Twibbon',rules?.require_twibbon?'Wajib':'Opsional / tidak ditentukan'],['Social proof',rules?.require_social_proof?'Wajib':'Opsional / tidak ditentukan'],['Kuota',rules?.max_participants?Number(rules.max_participants).toLocaleString('id-ID'):'Tanpa batas khusus']].map(([l,v])=>`<div><span>${l}</span><strong>${v}</strong></div>`).join('')}</div></section>
      <section class="panel-card detail-panel-v46 reward-panel-v46"><div class="panel-head"><div><span class="eyebrow">REWARD</span><h2>Hadiah & penghargaan</h2><p>Reward yang diberikan untuk peserta terpilih.</p></div></div><div class="reward-list reward-list-v46">${rewards.length?rewards.map((r,i)=>`<div class="reward-item reward-item-v46"><span class="reward-rank">${esc(r.rank_code||String(i+1))}</span><div><strong>${esc(r.title||'Reward')}</strong><small>${Number(r.points||0).toLocaleString('id-ID')} points${r.emblem_name?' · '+esc(r.emblem_name):''}</small></div><span class="reward-star">✦</span></div>`).join(''):'<div class="reward-empty-v46"><div>✦</div><strong>Reward belum dipublikasikan</strong><span>Penyelenggara belum mengisi reward kompetisi.</span></div>'}</div></section>
    </section>
    <section class="detail-grid-v46 detail-grid-bottom"><section class="panel-card detail-panel-v46"><div class="panel-head"><div><span class="eyebrow">CHECKLIST</span><h2>Yang perlu disiapkan</h2><p>Pastikan semuanya siap sebelum mendaftar.</p></div></div><div class="prep-grid-v46"><div><span>01</span><strong>Data diri</strong><small>Nama, kelas, dan sekolah harus sesuai profil.</small></div><div><span>02</span><strong>Dokumen / twibbon</strong><small>Siapkan bukti sesuai aturan kompetisi.</small></div><div><span>03</span><strong>Ikuti timeline</strong><small>Perhatikan batas pendaftaran dan pengumuman.</small></div></div></section><section class="panel-card detail-panel-v46"><div class="panel-head"><div><span class="eyebrow">SUPPORT</span><h2>Punya pertanyaan?</h2></div></div><div class="support-callout-v46"><strong>Perlu bantuan?</strong><p>Informasi penyelenggara akan ditampilkan di tahap pendaftaran saat tersedia.</p><a href="${window.SYKA_ROUTER.href('/profile')}" class="text-link">Cek profil saya →</a></div></section></section>`;
    document.getElementById('share-competition')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(window.location.href);window.SYKA_TOAST.show('Link kompetisi disalin.','success');}catch(_){window.SYKA_TOAST.show('Salin URL dari address bar.','info');}});
  }
  window.SYKA_PAGE_COMPETITION={render};
})();
