(function(){
  const U=()=>window.SYKA_UTILS;const esc=x=>U().escapeHtml(x);const fmt=x=>U().formatNumber(x);
  function avatarHtml(p){const url=p?.avatar_url||'';return `<span class="feed-avatar">${url?`<img src="${esc(url)}" alt="">`:esc(U().initials(p?.full_name||'Sykabelajar'))}</span>`;}
  function feedCard(kind,item,index){
    const isComp=kind==='competition';
    const title=isComp?item.title:(item.title||item.badge||'Update Sykabelajar');
    const text=isComp?(item.short_description||item.description||'Kompetisi terbaru di Sykabelajar.'):(item.subtitle||item.description||'Informasi terbaru dari Sykabelajar.');
    const href=isComp?window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(item.slug||'')):window.SYKA_ROUTER.href('/lomba');
    return `<article class="social-post ${isComp?'post-competition':'post-update'}"><div class="social-post-head">${avatarHtml({full_name:isComp?(item.organizer_name||'Penyelenggara'):'Sykabelajar',avatar_url:item.organizer_avatar_url})}<div class="social-post-meta"><strong>${esc(isComp?(item.organizer_name||'Penyelenggara'):'Sykabelajar')}</strong><span>${esc(isComp?'· Lomba terbaru':'· Update platform')}</span><time>${esc(U().formatDate(item.created_at||item.published_at||new Date().toISOString()))}</time></div><button class="feed-more" type="button" aria-label="Lainnya">•••</button></div><a class="social-post-body" href="${href}"><span class="post-kicker">${esc(isComp?'LOMBA':'UPDATE')}</span><h3>${esc(title)}</h3><p>${esc(text)}</p>${item.image_url?`<div class="post-media"><img src="${esc(item.image_url)}" loading="lazy" alt=""></div>`:''}</a><div class="social-post-stats"><button type="button" disabled><span>♡</span> ${fmt(item.like_count||0)}</button><button type="button" disabled><span>◌</span> ${fmt(item.comment_count||0)}</button><button type="button" data-share-post="${esc(title)}"><span>↗</span> Bagikan</button></div></article>`;
  }
  async function render(root){
    root.innerHTML=`<div class="home-x-layout"><aside class="home-rail home-rail-left"><section class="x-user-card" id="home-left-profile"><div class="x-cover"></div><div class="x-user-body"><div class="x-avatar-lg" id="home-user-avatar">S</div><strong id="home-user-name">Sykabelajar</strong><small id="home-user-handle">@sykabelajar</small><div class="x-user-stats"><span><b id="home-following">0</b><small>Mengikuti lomba</small></span><span><b id="home-certificates">0</b><small>Sertifikat</small></span></div><a class="btn btn-secondary btn-block btn-sm" href="${window.SYKA_ROUTER.href('/profile')}">Lihat profil</a></div></section></aside><main class="home-feed"><section class="home-feed-header"><div><span class="eyebrow">DISCOVERY</span><h1>Beranda</h1><p>Temukan lomba, pengumuman, dan rekam prestasi dalam satu alur.</p></div><div class="home-feed-filters" role="tablist"><button class="active" data-home-filter="all" type="button">Semua</button><button data-home-filter="competition" type="button">Lomba</button><button data-home-filter="update" type="button">Update</button></div></section>${((window.SYKA_STATE.getState().auth.roles||[]).includes('admin')|| (window.SYKA_STATE.getState().auth.roles||[]).includes('organizer_member'))?`<section class="composer-compact composer-role-allowed"><div class="composer-avatar">S</div><button type="button" id="home-status-create" class="composer-input">Bagikan pembaruan resmi…</button></section>`:''}<div id="home-feed-list" class="home-feed-list"></div></main><aside class="home-rail home-rail-right"><section class="x-panel"><div class="x-panel-head"><h3>Statistik platform</h3></div><div id="home-stats" class="stats-compact"><div><b>—</b><span>Siswa</span></div><div><b>—</b><span>Sekolah</span></div><div><b>—</b><span>Penerima prestasi</span></div><div><b>—</b><span>Juara</span></div></div></section><section class="x-panel"><div class="x-panel-head"><h3>Lomba sedang populer</h3><a href="${window.SYKA_ROUTER.href('/lomba')}">Lihat semua</a></div><div id="home-trending" class="trending-list"></div></section><section class="x-panel x-muted-panel"><span class="eyebrow">SYKABELAJAR</span><h3>Belajar. Berkompetisi. Berprestasi.</h3><p>Gunakan misi untuk mengumpulkan XP/Koin Edu dan bangun rekam prestasi.</p><a class="btn btn-primary btn-sm" href="${window.SYKA_ROUTER.href('/tugas')}">Buka Misi</a></section></aside></div>`;
    document.getElementById('home-status-create')?.addEventListener('click',()=>window.SYKA_TOAST.show('Editor posting resmi akan tersedia dari control plane Admin/Penyelenggara.','info'));
    const list=document.getElementById('home-feed-list');list.innerHTML=[1,2,3].map(()=>'<div class="social-post skeleton-post"></div>').join('');
    const auth=window.SYKA_STATE.getState().auth;if(auth.user){const p=auth.profile||{};document.getElementById('home-user-name').textContent=p.full_name||auth.user.email?.split('@')[0]||'Pengguna';document.getElementById('home-user-handle').textContent='@'+(p.username||'user');if(p.avatar_url)document.getElementById('home-user-avatar').innerHTML=`<img src="${esc(p.avatar_url)}" alt="">`;}
    try{
      const [stats,slides,rows]=await Promise.allSettled([window.SYKA_CONTROL_SERVICE.platformStats(),window.SYKA_CONTROL_SERVICE.listSlides({admin:false}),window.SYKA_COMPETITION_SERVICE.list({limit:9})]);
      if(stats.status==='fulfilled'){const s=stats.value||{};const vals=[s.total_students,s.total_schools,s.total_award_recipients,s.total_champions];document.querySelectorAll('#home-stats b').forEach((el,i)=>el.textContent=fmt(vals[i]||0));}
      const competitions=rows.status==='fulfilled'?(rows.value||[]):[];document.getElementById('home-trending').innerHTML=competitions.slice(0,5).map((c,i)=>`<a class="trend-item" href="${window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(c.slug||''))}"><span>${i+1}</span><div><strong>${esc(c.title)}</strong><small>${esc(c.status||'')}</small></div></a>`).join('')||'<div class="empty-mini">Belum ada lomba.</div>';
      const updates=slides.status==='fulfilled'?(slides.value||[]):[];let active='all';const paint=()=>{const filtered=[...(active==='competition'||active==='all'?competitions:[]).map(c=>({kind:'competition',item:c})),...(active==='update'||active==='all'?updates:[]).map(s=>({kind:'update',item:s}))];list.innerHTML=filtered.length?filtered.slice(0,12).map((x,i)=>feedCard(x.kind,x.item,i)).join(''):'<div class="empty-card"><strong>Belum ada discovery</strong><span>Konten akan tampil ketika ada lomba atau update resmi.</span></div>';list.querySelectorAll('[data-share-post]').forEach(b=>b.addEventListener('click',async()=>{const text=b.dataset.sharePost;if(navigator.share){try{await navigator.share({title:text,url:location.href});}catch(_){}}else{await navigator.clipboard?.writeText(location.href);window.SYKA_TOAST.show('Link disalin.','success');}}));};paint();document.querySelectorAll('[data-home-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-home-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');active=btn.dataset.homeFilter;paint();}));
    }catch(error){list.innerHTML=`<div class="empty-card"><strong>Discovery belum tersedia</strong><span>${esc(error.message||'Coba lagi nanti.')}</span><button type="button" class="btn btn-secondary btn-sm" id="retry-home">Coba lagi</button></div>`;document.getElementById('retry-home')?.addEventListener('click',()=>window.SYKA_ROUTER.refresh());}
  }
  window.SYKA_PAGE_HOME={render};
})();
