(function(){
  const U=()=>window.SYKA_UTILS;const esc=x=>U().escapeHtml(x);const fmt=x=>U().formatNumber(x);
  function avatarHtml(p){const url=p?.avatar_url||'';return `<span class="feed-avatar">${url?`<img src="${esc(url)}" alt="" loading="lazy">`:esc(U().initials(p?.full_name||'Sykabelajar'))}</span>`;}
  function competitionCard(item){
    const href=window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(item.slug||''));
    const title=item.title||'Kompetisi';
    const poster=item.poster||item.poster_url||item.image_url||'';
    const transformed=poster?U().cloudinaryTransform(poster,{width:900,height:506,crop:'fill'}):'';
    return `<article class="bolt-card competition-card home-competition-card"><a class="competition-card-media" href="${href}" aria-label="Lihat ${esc(title)}">${transformed?`<img src="${esc(transformed)}" alt="" loading="lazy">`:'<div class="competition-media-placeholder"><span>✦</span><small>Sykabelajar.id</small></div>'}<span class="competition-status-overlay ${U().statusClass(item.status)}">${esc(String(item.status||'').replaceAll('_',' '))}</span></a><div class="competition-card-body"><div class="chip-row"><span class="chip">${esc(item.category||'Kompetisi')}</span></div><h3><a href="${href}">${esc(title)}</a></h3><p>${esc(item.short_description||item.description||'Temukan persyaratan, timeline, hadiah, dan mekanisme kompetisi.')}</p><div class="competition-card-meta"><span><b>Mulai</b>${esc(U().formatDate(item.starts_at||item.startsAt))}</span><span><b>Daftar s/d</b>${esc(U().formatDate(item.registration_ends_at||item.registrationEndsAt))}</span></div><a class="btn btn-primary btn-block btn-sm" href="${href}">Lihat detail <span>→</span></a></div></article>`;
  }
  function postCard(item){
    const href=item.competition_id&&item.slug?window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(item.slug)):window.SYKA_ROUTER.href('/home');
    const name=item.organizer_name||item.author_name||'Sykabelajar';
    return `<article class="social-post post-update bolt-card"><div class="social-post-head">${avatarHtml({full_name:name,avatar_url:item.organizer_avatar_url||item.author_avatar_url})}<div class="social-post-meta"><strong>${esc(name)}</strong><span>· Update Sykabelajar</span><time>${esc(U().formatDate(item.created_at||item.published_at||new Date().toISOString()))}</time></div><button class="feed-more" type="button" aria-label="Lainnya">•••</button></div><a class="social-post-body" href="${href}"><span class="post-kicker">UPDATE</span><h3>${esc(item.title||item.badge||'Update Sykabelajar')}</h3><p>${esc(item.subtitle||item.description||'Informasi terbaru dari Sykabelajar.')}</p>${item.image_url?`<div class="post-media"><img src="${esc(item.image_url)}" loading="lazy" alt=""></div>`:''}</a><div class="social-post-stats"><button type="button" disabled>♡ ${fmt(item.like_count||0)}</button><button type="button" disabled>◌ ${fmt(item.comment_count||0)}</button><button type="button" data-share-post="${esc(item.title||'Sykabelajar')}">↗ Bagikan</button></div></article>`;
  }
  async function render(root){
    const auth=window.SYKA_STATE.getState().auth;
    root.innerHTML=`<div class="bolt-home-layout"><main class="bolt-home-main"><section class="home-welcome"><div class="eyebrow">DISCOVERY</div><h1>Beranda</h1><p>Temukan lomba, misi, dan prestasi dalam satu ruang belajar.</p></section><section class="home-tabs-card bolt-card"><div class="home-tabs"><button class="active" data-home-tab="lomba" type="button">Lomba</button><button data-home-tab="prestasi" type="button">Prestasi</button></div></section><section class="quick-actions"><a class="quick-action bolt-card" href="${window.SYKA_ROUTER.href('/lomba')}"><span class="quick-action-icon">◈</span><div><strong>Ikuti kompetisi</strong><small>Jelajahi lomba yang sedang dibuka dan pilih yang sesuai.</small></div><span class="quick-arrow">→</span></a><a class="quick-action bolt-card" href="${window.SYKA_ROUTER.href('/tugas')}"><span class="quick-action-icon">✦</span><div><strong>Selesaikan misi harian</strong><small>Dapatkan XP dan Koin Edu dari aktivitas yang tersedia.</small></div><span class="quick-arrow">→</span></a></section><section class="content-section"><div class="section-title"><div><span class="eyebrow">KOMPETISI</span><h2>Kompetisi pilihan</h2><p>Data diambil langsung dari backend Sykabelajar.</p></div><a class="text-link" href="${window.SYKA_ROUTER.href('/lomba')}">Lihat semua →</a></div><div id="home-competition-grid" class="card-grid"></div></section><section class="content-section" id="home-feed-section"><div class="section-title"><div><span class="eyebrow">UPDATE</span><h2>Update terbaru</h2></div></div><div id="home-feed-list" class="home-feed-list"></div></section></main><aside class="home-right-rail"><section class="panel-card home-profile-summary" id="home-profile-summary"><div class="profile-summary-cover"></div><div class="profile-summary-body"><div class="x-avatar-lg" id="home-user-avatar">S</div><strong id="home-user-name">Pengguna</strong><small id="home-user-handle">@user</small><a class="btn btn-secondary btn-sm btn-block" href="${window.SYKA_ROUTER.href('/profile')}">Lihat profil</a></div></section><section class="panel-card"><div class="section-title compact"><div><span class="eyebrow">RINGKASAN</span><h2>Progress kamu</h2></div></div><div id="home-progress-stats" class="home-progress-stats"><div><b>—</b><small>XP</small></div><div><b>—</b><small>Koin Edu</small></div><div><b>—</b><small>Prestasi</small></div></div></section><section class="panel-card"><div class="section-title compact"><div><span class="eyebrow">TRENDING</span><h2>Lomba populer</h2></div><a class="text-link" href="${window.SYKA_ROUTER.href('/lomba')}">Semua</a></div><div id="home-trending" class="trending-list"></div></section></aside></div>`;
    if(auth.user){const p=auth.profile||{};const name=p.full_name||auth.user.user_metadata?.full_name||auth.user.email?.split('@')[0]||'Pengguna';const a=document.getElementById('home-user-avatar');document.getElementById('home-user-name').textContent=name;document.getElementById('home-user-handle').textContent='@'+(p.username||'user');if(p.avatar_url)a.innerHTML=`<img src="${esc(p.avatar_url)}" alt="" loading="lazy">`;}
    const grid=document.getElementById('home-competition-grid');grid.innerHTML=[0,1,2].map(()=>'<div class="competition-card skeleton-card"></div>').join('');
    const feed=document.getElementById('home-feed-list');feed.innerHTML=[0,1,2].map(()=>'<div class="social-post skeleton-post"></div>').join('');
    try{
      const [competitions,updates,tasks,awards]=await Promise.allSettled([
        window.SYKA_COMPETITION_SERVICE.list({limit:9}),
        window.SYKA_CONTROL_SERVICE.listSlides({admin:false}),
        auth.user?window.SYKA_TASK_SERVICE.listTasks():Promise.resolve([]),
        auth.user&&window.SYKA_AWARD_SERVICE?.getAwards?window.SYKA_AWARD_SERVICE.getAwards(auth.user.id):Promise.resolve([])
      ]);
      const comps=competitions.status==='fulfilled'?(competitions.value||[]):[];
      grid.innerHTML=comps.length?comps.slice(0,6).map(competitionCard).join(''):window.SYKA_EMPTY.render({title:'Belum ada kompetisi',text:'Kompetisi publik akan muncul di sini setelah dipublikasikan.'});
      document.getElementById('home-trending').innerHTML=comps.slice(0,5).map((c,i)=>`<a class="trend-item" href="${window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(c.slug||''))}"><span>${i+1}</span><div><strong>${esc(c.title||'Kompetisi')}</strong><small>${esc(String(c.status||'').replaceAll('_',' '))}</small></div></a>`).join('')||'<div class="empty-mini">Belum ada lomba.</div>';
      const p=auth.profile||{};const awardRows=awards.status==='fulfilled'?(awards.value||[]):[];const xp=Number(p.xp_balance??p.xp??p.total_xp??0);const coins=Number(p.edu_coin_balance??p.edu_coins??p.coin_balance??0);document.querySelectorAll('#home-progress-stats b').forEach((el,i)=>el.textContent=U().formatNumber([xp,coins,awardRows.length][i]||0));
      const up=updates.status==='fulfilled'?(updates.value||[]):[];feed.innerHTML=up.length?up.slice(0,6).map(postCard).join(''):(comps.length?comps.slice(0,4).map(c=>`<article class="social-post post-competition bolt-card"><div class="social-post-head">${avatarHtml({full_name:c.organizer_name||'Penyelenggara',avatar_url:c.organizer_avatar_url})}<div class="social-post-meta"><strong>${esc(c.organizer_name||'Penyelenggara')}</strong><span>· Lomba terbaru</span></div></div><a class="social-post-body" href="${window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(c.slug||''))}"><span class="post-kicker">LOMBA</span><h3>${esc(c.title)}</h3><p>${esc(c.short_description||c.description||'Kompetisi terbaru di Sykabelajar.')}</p></a></article>`).join(''):'<div class="empty-card"><strong>Belum ada update</strong><span>Update resmi akan muncul di sini.</span></div>');
      document.querySelectorAll('[data-home-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-home-tab]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(btn.dataset.homeTab==='prestasi'){feed.innerHTML=awardRows.length?awardRows.slice(0,6).map(a=>`<article class="social-post bolt-card"><div class="social-post-body"><span class="post-kicker">PRESTASI</span><h3>${esc(a.title||a.achievement_title||'Prestasi')}</h3><p>${esc(a.description||'Pencapaian kamu di Sykabelajar.')}</p></div></article>`).join(''):'<div class="empty-card"><strong>Belum ada prestasi</strong><span>Selesaikan kompetisi dan misi untuk membangun rekam prestasi.</span></div>';}else{feed.innerHTML=up.length?up.slice(0,6).map(postCard).join(''):'<div class="empty-card"><strong>Belum ada update</strong><span>Update resmi akan muncul di sini.</span></div>';}}));
      feed.querySelectorAll('[data-share-post]').forEach(b=>b.addEventListener('click',async()=>{try{if(navigator.share)await navigator.share({title:b.dataset.sharePost,url:location.href});else{await navigator.clipboard?.writeText(location.href);window.SYKA_TOAST.show('Link disalin.','success');}}catch(_){}}));
    }catch(e){grid.innerHTML=window.SYKA_EMPTY.render({title:'Data belum tersedia',text:e.message||'Coba lagi nanti.'});feed.innerHTML=window.SYKA_EMPTY.render({title:'Feed belum tersedia',text:e.message||'Coba lagi nanti.'});}
  }
  window.SYKA_PAGE_HOME={render};
})();