(function(){
  const u=()=>window.SYKA_UTILS,esc=u().escapeHtml,fmt=u().formatNumber;
  async function render(root){
    root.innerHTML=`<section class="hero-v3"><div class="hero-main"><span class="eyebrow">SYKABELAJAR.ID · LEARN → COMPETE → ACHIEVE</span><h1>Belajar. Berkompetisi.<br><em>Berprestasi.</em></h1><p>Temukan kompetisi yang sesuai, ikuti prosesnya dengan nyaman, lalu bangun rekam prestasi yang bisa diverifikasi.</p><div class="hero-actions"><a class="btn btn-primary" href="${window.SYKA_ROUTER.href('/lomba')}">Jelajahi Lomba <span>→</span></a><a class="btn btn-secondary" href="${window.SYKA_ROUTER.href('/juara')}">Lihat Juara</a></div><div class="hero-stats" id="hero-stats">${[['total_students','Siswa terdaftar'],['total_schools','Sekolah terdaftar'],['total_award_recipients','Penerima prestasi'],['total_champions','Juara']].map(([,l])=>`<div class="stat-card"><strong>—</strong><span>${l}</span></div>`).join('')}</div></div><div class="hero-side" id="hero-promo"><div class="promo-placeholder"><span class="eyebrow">PROMO</span><h3>Ruang promosi tersedia</h3><p>Admin bisa memasukkan poster acara, campaign, deadline, atau pengumuman penting di sini.</p><span class="promo-hint">Optimized untuk poster landscape / 16:9</span></div></div></section><section class="content-section"><div class="section-title"><div><span class="eyebrow">DISCOVERY</span><h2>Lomba terbaru</h2><p>Kompetisi publik diambil langsung dari Supabase.</p></div><a class="text-link" href="${window.SYKA_ROUTER.href('/lomba')}">Lihat semua →</a></div><div id="home-competitions" class="card-grid"></div></section><section class="feature-strip"><a href="${window.SYKA_ROUTER.href('/juara')}" class="feature-item"><span>♛</span><div><strong>Top 50 juara</strong><small>Layout podium dan pagination sudah siap.</small></div>→</a><a href="${window.SYKA_ROUTER.href('/prestasi')}" class="feature-item"><span>✦</span><div><strong>Prestasi pribadi</strong><small>Awards dan proof of achievement dalam satu tempat.</small></div>→</a><a href="${window.SYKA_ROUTER.href('/verifikasi/demo')}" class="feature-item"><span>✓</span><div><strong>Verifikasi</strong><small>Validasi certificate dengan kode publik.</small></div>→</a></section>`;
    const list=document.getElementById('home-competitions');list.innerHTML=[0,1,2].map(()=>window.SYKA_SKELETON.card()).join('');
    try{const [stats,slides,rows]=await Promise.all([window.SYKA_CONTROL_SERVICE.platformStats(),window.SYKA_CONTROL_SERVICE.listSlides({admin:false}),window.SYKA_COMPETITION_SERVICE.list({limit:6})]);const keys=['total_students','total_schools','total_award_recipients','total_champions'];document.querySelectorAll('#hero-stats .stat-card strong').forEach((el,i)=>el.textContent=fmt(stats[keys[i]]));renderPromo(slides);list.innerHTML=rows.length?rows.map(window.SYKA_COMPETITION_CARD.render).join(''):window.SYKA_EMPTY.render({title:'Belum ada kompetisi publik',text:'Saat organizer menerbitkan kompetisi, kartu lomba akan muncul otomatis.',actionHtml:`<a class="btn btn-secondary btn-sm" href="${window.SYKA_ROUTER.href('/lomba')}">Buka katalog</a>`});}catch(error){document.querySelectorAll('#hero-stats .stat-card strong').forEach(x=>x.textContent='—');list.innerHTML=window.SYKA_EMPTY.render({title:'Data publik belum tersambung',text:error.message||'Coba lagi beberapa saat lagi.',actionHtml:'<button class="btn btn-secondary btn-sm" id="retry-home">Coba lagi</button>'});document.getElementById('retry-home')?.addEventListener('click',()=>window.SYKA_ROUTER.refresh());}
  }
  function renderPromo(slides){const el=document.getElementById('hero-promo');if(!slides.length)return;let index=0;const paint=()=>{const s=slides[index];el.innerHTML=`<div class="promo-frame"><img src="${esc(s.image_url)}" alt="${esc(s.title)}" loading="eager"><div class="promo-shade"></div><div class="promo-copy"><span class="promo-badge">${esc(s.badge||'PROMO')}</span><h3>${esc(s.title)}</h3>${s.subtitle?`<p>${esc(s.subtitle)}</p>`:''}${s.cta_label?`<a class="btn btn-white btn-sm" href="${window.SYKA_ROUTER.href(s.cta_route||'/lomba')}">${esc(s.cta_label)} →</a>`:''}</div><div class="promo-dots">${slides.map((_,i)=>`<button type="button" class="promo-dot ${i===index?'active':''}" data-i="${i}" aria-label="Slide ${i+1}"></button>`).join('')}</div></div>`;el.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{index=Number(b.dataset.i);paint();});};paint();if(slides.length>1)setInterval(()=>{index=(index+1)%slides.length;paint();},5000);}
  window.SYKA_PAGE_HOME={render};
})();
