(function(){
  const svc=()=>window.SYKA_CONTROL_SERVICE;const esc=window.SYKA_UTILS.escapeHtml;const fmt=window.SYKA_UTILS.formatDateTime;
  const tabs=[['dashboard','Dashboard'],['competitions','Kompetisi'],['participants','Peserta'],['questions','Soal'],['grading','Grading'],['results','Hasil'],['awards','Awards'],['certificates','Sertifikat'],['twibbon','Twibbon'],['notifications','Notifikasi'],['plan','Plan & Usage']];
  const transitions={DRAFT:['PUBLISHED','SUSPENDED','CANCELLED'],PUBLISHED:['REGISTRATION_OPEN','SUSPENDED','CANCELLED'],REGISTRATION_OPEN:['REGISTRATION_CLOSED','SUSPENDED','CANCELLED'],REGISTRATION_CLOSED:['LIVE','SUSPENDED','CANCELLED'],LIVE:['SUBMISSION_CLOSED','SUSPENDED','CANCELLED'],SUBMISSION_CLOSED:['GRADING','SUSPENDED','CANCELLED'],GRADING:['RESULT_PUBLISHED','SUSPENDED'],RESULT_PUBLISHED:['ARCHIVED','SUSPENDED'],SUSPENDED:['DRAFT','PUBLISHED','REGISTRATION_OPEN','REGISTRATION_CLOSED','LIVE','SUBMISSION_CLOSED','GRADING','RESULT_PUBLISHED','CANCELLED']};
  async function membership(){const a=window.SYKA_STATE.getState().auth;const list=await svc().listMyOrganizerMemberships(a.user?.id).catch(()=>[]);return list[0]?.organizer_id||null;}
  function shell(tab){return `<div class="control-head"><div><span class="eyebrow">ORGANIZER CONTROL PLANE</span><h1>Panel Penyelenggara</h1><p>Kelola kompetisi, peserta, soal, hasil, awards, certificate, twibbon, dan entitlement dari satu workspace.</p></div><div class="control-head-meta"><span class="security-badge">Plan & permission server-side</span></div></div><div class="control-tabs">${tabs.map(([k,l])=>`<button type="button" class="control-tab ${tab===k?'active':''}" data-tab="${k}">${l}</button>`).join('')}</div><div id="organizer-content"></div>`;}
  async function render(root){
    const auth=window.SYKA_STATE.getState().auth;
    if(!auth.user){
      root.innerHTML=window.SYKA_EMPTY.render({title:'Masuk diperlukan',text:'Panel penyelenggara membutuhkan akun yang memiliki workspace.',actionHtml:'<button class="btn btn-primary" id="org-login">Masuk</button>'});
      document.getElementById('org-login')?.addEventListener('click',()=>window.SYKA_APP.openAuth('login',{target:'/organizer'}));
      return;
    }
    if(!auth.roles.includes('organizer_member')&&!auth.roles.includes('admin')){
      root.innerHTML=window.SYKA_EMPTY.render({title:'Akses belum tersedia',text:'Akun ini belum memiliki jalur Penyelenggara. Daftar sebagai Penyelenggara atau minta Admin menambahkan role.'});
      return;
    }

    const q=window.SYKA_STATE.getState().route.query||{};
    let orgRows=[];
    let orgId=q.organizer||null;

    try{
      orgRows=auth.roles.includes('admin')?await svc().listOrganizers():await svc().listMyOrganizerMemberships(auth.user.id);
      if(!orgId) orgId=orgRows[0]?.id||orgRows[0]?.organizer_id||null;

      if(!orgId){
        root.innerHTML=window.SYKA_EMPTY.render({
          title:'Belum ada workspace penyelenggara',
          text:auth.roles.includes('admin')?'Belum ada organizer yang terdaftar. Buat akun penyelenggara terlebih dahulu atau buat workspace dari backend.':'Workspace penyelenggara akun ini belum tersedia.'
        });
        return;
      }

      if(auth.roles.includes('admin')&&!q.organizer){
        window.SYKA_ROUTER.navigate('/organizer',{organizer:orgId,tab:q.tab||'dashboard'});
        return;
      }

      const activePlan=await svc().listActiveOrganizerPlan(orgId).catch(()=>null);
      const pendingPlanOrder=!activePlan?await svc().getPendingOrganizerPlanOrder(orgId).catch(()=>null):null;
      const tab=tabs.some(([k])=>k===q.tab)?q.tab:'dashboard';

      // Package selection must happen before the control-plane settings/tabs.
      if(!activePlan&&tab!=='plan'){
        root.innerHTML=`<div class="control-head"><div><span class="eyebrow">ORGANIZER ONBOARDING</span><h1>${pendingPlanOrder?'Pembayaran sedang direview':'Pilih paket workspace'}</h1><p>${pendingPlanOrder?'Pesanan paket sudah diterima. Paket akan aktif setelah Admin memverifikasi bukti transfer.':'Capability dan quota workspace berasal dari paket yang dipilih. Free dapat langsung aktif; Premium/Pro memerlukan pembayaran manual dan review Admin.'}</p></div><div class="control-head-meta">${auth.roles.includes('admin')?workspaceSwitcher(orgRows,orgId):'<span class="security-badge">Workspace aktif</span>'}</div></div><div id="plan-choice-root"></div>`;
        if(pendingPlanOrder){
          const item=(pendingPlanOrder.order_items||[])[0];
          document.getElementById('plan-choice-root').innerHTML=`<section class="plan-pending-card-v46"><div class="pending-icon-v46">⌛</div><span class="eyebrow">PENDING PAYMENT REVIEW</span><h2>${esc(item?.name||'Paket penyelenggara')}</h2><p>Order <b>#${esc(String(pendingPlanOrder.id).slice(0,10))}</b> sudah diterima pada ${fmt(pendingPlanOrder.created_at)}.</p><div class="plan-pending-meta-v46"><div><span>Status</span><strong>${esc(pendingPlanOrder.payment_proof_status||'SUBMITTED')}</strong></div><div><span>WhatsApp</span><strong>${esc(pendingPlanOrder.contact_whatsapp||'—')}</strong></div><div><span>Total</span><strong>Rp ${Number(pendingPlanOrder.total||0).toLocaleString('id-ID')}</strong></div></div><div class="form-actions"><button class="btn btn-secondary" id="view-orders">Lihat pesanan</button><button class="btn btn-ghost" id="change-pending-plan">Pilih paket lain</button></div></section>`;
          document.getElementById('view-orders').onclick=()=>window.SYKA_ROUTER.navigate('/pesanan');
          document.getElementById('change-pending-plan').onclick=()=>renderPlanChoice(document.getElementById('plan-choice-root'),orgId);
        }else{
          await renderPlanChoice(document.getElementById('plan-choice-root'),orgId);
        }
        return;
      }

      root.innerHTML=shell(tab);
      const tabsRoot=root.querySelectorAll('[data-tab]');
      tabsRoot.forEach(b=>b.onclick=()=>window.SYKA_ROUTER.navigate('/organizer',{organizer:orgId,tab:b.dataset.tab}));
      const headMeta=root.querySelector('.control-head-meta');
      if(headMeta){
        headMeta.innerHTML=`${auth.roles.includes('admin')?workspaceSwitcher(orgRows,orgId):'<span class="workspace-chip">Workspace aktif</span>'}<span class="security-badge">Paket ${esc(activePlan?.plan_code||'FREE')} · server-side</span>`;
      }
      await renderTab(document.getElementById('organizer-content'),tab,orgId);
    }catch(error){
      document.getElementById('organizer-content')?.replaceChildren();
      root.innerHTML=window.SYKA_EMPTY.render({title:'Modul gagal dimuat',text:error.message||'Periksa workspace, paket, dan RLS lalu coba lagi.'});
    }
  }

  function workspaceSwitcher(rows,selected){
    const options=rows.map(r=>{const id=r.id||r.organizer_id;const label=r.name||r.organizers?.name||id;return `<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`;}).join('');
    setTimeout(()=>document.getElementById('organizer-workspace-select')?.addEventListener('change',e=>window.SYKA_ROUTER.navigate('/organizer',{organizer:e.target.value,tab:'dashboard'})),0);
    return `<label class="workspace-picker"><span>Workspace</span><select id="organizer-workspace-select">${options}</select></label>`;
  }

  function planRank(code){return ({FREE:0,PREMIUM:1,PRO:2}[String(code||'').toUpperCase()]??0);}
  async function renderPlanChoice(root,orgId){
    const [catalog,entitlements,active]=await Promise.all([svc().listPlanCatalog(),svc().listEntitlements(),svc().listActiveOrganizerPlan(orgId).catch(()=>null)]);
    const current=active?.plan_code||null;
    const currentRank=planRank(current);
    const ordered=(catalog||[]).filter(p=>!current||planRank(p.plan_code)>=currentRank).sort((a,b)=>planRank(a.plan_code)-planRank(b.plan_code));
    root.innerHTML=`<section class="plan-onboarding-v47"><div class="plan-choice-intro-v47"><div><span class="eyebrow">WORKSPACE PLAN</span><h2>${current?'Upgrade paket workspace':'Pilih paket workspace'}</h2><p>${current?'Paket lebih rendah tidak dapat dipilih kembali. Kamu hanya bisa mempertahankan paket saat ini atau upgrade ke tingkat yang lebih tinggi.':'Pilih paket yang sesuai. Free dapat langsung aktif; Premium/Pro memerlukan pembayaran manual dan review Admin.'}</p></div>${current?`<span class="status-pill status-success">Saat ini: ${esc(current)}</span>`:''}</div><div class="plan-choice-grid-v47">${ordered.map(plan=>{
      const items=entitlements.filter(e=>e.plan_code===plan.plan_code);
      const paid=Number(plan.monthly_price||0)>0;
      const isCurrent=current===plan.plan_code;
      const higher=current&&planRank(plan.plan_code)>currentRank;
      return `<article class="plan-choice-card-v47 ${plan.plan_code==='PREMIUM'?'featured':''} ${isCurrent?'current':''}"><div class="plan-choice-top"><span class="plan-badge ${plan.plan_code.toLowerCase()}">${esc(plan.badge||plan.plan_code)}</span><span class="plan-choice-label">${isCurrent?'DIGUNAKAN':paid?'UPGRADE':'TERSEDIA'}</span></div><h2>${esc(plan.name)}</h2><p>${esc(plan.description||'Paket workspace penyelenggara.')}</p><div class="plan-price-v46">${paid?`Rp ${Number(plan.monthly_price).toLocaleString('id-ID')}<small>/ bulan</small>`:'Gratis'}</div><div class="plan-benefit-list-v46">${items.slice(0,7).map(e=>`<div><span>✓</span><strong>${esc(e.capability.replaceAll('_',' '))}</strong><small>${e.limit_value==null?'Tanpa batas':`Limit ${Number(e.limit_value).toLocaleString('id-ID')}`}</small></div>`).join('')||'<div class="muted">Capability belum diatur.</div>'}</div><button type="button" class="btn ${isCurrent?'btn-secondary':higher?'btn-primary':'btn-ghost'} btn-block" data-select-plan="${esc(plan.plan_code)}" ${isCurrent?'disabled':''}>${isCurrent?'Digunakan':higher?'Beli / Upgrade':'Tidak tersedia'}</button></article>`;
    }).join('')}</div><div class="plan-choice-note"><strong>Upgrade only</strong><span>Downgrade tidak tersedia melalui self-service. Perubahan tier dirancang agar billing, entitlement, dan histori workspace tetap konsisten.</span></div></section>`;
    root.querySelectorAll('[data-select-plan]').forEach(b=>b.onclick=()=>selectPlan(orgId,b.dataset.selectPlan));
  }

  async function selectPlan(orgId,planCode){
    if(planCode==='FREE'){
      try{await svc().chooseOrganizerPlan(orgId,'FREE');window.SYKA_TOAST.show('Paket Free aktif.','success');window.SYKA_ROUTER.navigate('/organizer',{organizer:orgId,tab:'dashboard'});}catch(e){window.SYKA_TOAST.show(e.message||'Gagal mengaktifkan paket.','error');}
      return;
    }
    const catalog=await svc().listPlanCatalog();
    const plan=catalog.find(p=>p.plan_code===planCode);
    if(!plan)return;
    window.SYKA_MODAL.open({title:`Aktifkan ${plan.name}`,wide:true,html:`<div class="plan-purchase-v46"><div class="purchase-price"><span>${esc(plan.name)}</span><strong>Rp ${Number(plan.monthly_price||0).toLocaleString('id-ID')} / bulan</strong></div><label>Nomor WhatsApp *<input id="plan-wa" inputmode="tel" placeholder="08xxxxxxxxxx"></label><div class="upload-field-card"><div><span class="eyebrow">BUKTI PEMBAYARAN</span><h3>Upload bukti transfer</h3><p>Gambar langsung diunggah ke Cloudinary. Tidak perlu memasukkan URL.</p></div><div class="upload-preview" id="plan-proof-preview"><div class="upload-placeholder"><span>↑</span><strong>Belum ada bukti</strong><small>PNG, JPG, WEBP • maksimal 8 MB</small></div></div><button type="button" class="btn btn-secondary" id="plan-proof-upload">Pilih gambar</button></div><div id="plan-purchase-feedback"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Batal</button><button type="button" class="btn btn-primary" id="plan-purchase-submit">Kirim untuk review</button></div></div>`,onOpen:b=>{let proof=null;b.querySelector('[data-close]').onclick=()=>window.SYKA_MODAL.close();b.querySelector('#plan-proof-upload').onclick=async()=>{try{proof=await window.SYKA_CLOUDINARY.openPaymentProofWidget();b.querySelector('#plan-proof-preview').innerHTML=`<img src="${esc(proof.secure_url)}" alt="Bukti pembayaran"><div class="upload-file-meta"><strong>${esc(proof.original_filename||'Bukti')}</strong></div>`;}catch(e){b.querySelector('#plan-purchase-feedback').innerHTML=`<div class="inline-error">${esc(e.message||'Upload gagal.')}</div>`;}};b.querySelector('#plan-purchase-submit').onclick=async()=>{const wa=b.querySelector('#plan-wa').value.trim();if(wa.length<8||!proof){b.querySelector('#plan-purchase-feedback').innerHTML='<div class="inline-error">Nomor WhatsApp dan bukti transfer wajib diisi.</div>';return;}const btn=b.querySelector('#plan-purchase-submit');btn.disabled=true;btn.innerHTML='<span class="spinner"></span> Mengirim…';try{const{data,error}=await window.SYKA_SUPABASE.get().rpc('create_organizer_plan_order',{p_organizer_id:orgId,p_plan_code:planCode,p_whatsapp:wa,p_proof_url:proof.secure_url,p_proof_public_id:proof.public_id,p_proof_width:proof.width,p_proof_height:proof.height,p_proof_version:String(proof.version||''),p_proof_resource_type:proof.resource_type||'image'});if(error)throw error;window.SYKA_MODAL.close();window.SYKA_TOAST.show(`Pesanan #${String(data.id).slice(0,8)} masuk review admin.`,'success');}catch(e){btn.disabled=false;btn.textContent='Kirim untuk review';b.querySelector('#plan-purchase-feedback').innerHTML=`<div class="inline-error">${esc(e.message||'Order gagal dibuat.')}</div>`;}};}});
  }
  async function renderTab(root,tab,orgId){const map={dashboard,competitions,participants,questions,grading,results,awards,certificates,twibbon,notifications,plan};return map[tab]?.(root,orgId);}
  async function dashboard(root,orgId){const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});const regs=await svc().listRegistrations({});const mineRegs=regs.filter(r=>comps.some(c=>c.id===r.competition_id));const attempts=await svc().listAttempts({});const mineAttempts=attempts.filter(a=>comps.some(c=>c.id===a.competition_id));root.innerHTML=`<div class="kpi-grid"><div class="kpi-card"><span>Kompetisi</span><strong>${comps.length}</strong><small>milik organizer</small></div><div class="kpi-card"><span>Pending peserta</span><strong>${mineRegs.filter(r=>r.status==='PENDING').length}</strong><small>perlu review</small></div><div class="kpi-card"><span>Attempt submitted</span><strong>${mineAttempts.filter(a=>a.status==='SUBMITTED').length}</strong><small>siap grading</small></div><div class="kpi-card"><span>Live</span><strong>${comps.filter(c=>c.status==='LIVE').length}</strong><small>kompetisi berjalan</small></div></div><section class="panel-card admin-section"><div class="panel-head"><div><span class="eyebrow">WORKSPACE</span><h2>Kompetisi aktif</h2></div><button class="btn btn-primary btn-sm" id="org-new-comp">+ Kompetisi</button></div><div class="mini-list">${comps.slice(0,8).map(c=>`<div class="mini-list-row"><div><strong>${esc(c.title)}</strong><small>${esc(c.category)} · ${esc(c.status)} · mulai ${fmt(c.starts_at)}</small></div><span class="status-pill ${window.SYKA_UTILS.statusClass(c.status)}">${esc(c.status)}</span></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada kompetisi',text:'Buat kompetisi pertama untuk organizer ini.'})}</div></section>`;document.getElementById('org-new-comp').onclick=()=>competitionModal(orgId);}
  async function competitions(root,orgId){
    const rows=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});
    root.innerHTML=`<div class="toolbar"><div><span class="eyebrow">WORKSPACE</span><h2>Kompetisi</h2><p>Kelola poster, timeline, konfigurasi, peserta, grading, dan state machine dari satu tempat.</p></div><button class="btn btn-primary" id="new-org-comp">+ Buat kompetisi</button></div><div class="data-table organizer-competition-list">${rows.map(c=>{const poster=window.SYKA_UTILS.cloudinaryTransform(c.poster_url,{width:120,height:80,crop:'fill'});return `<div class="data-row competition-admin-row"><div class="row-main"><div class="media-thumb">${poster?`<img src="${esc(poster)}" alt="" loading="lazy">`:'✦'}</div><div><div class="row-title"><strong>${esc(c.title)}</strong><span class="status-pill ${window.SYKA_UTILS.statusClass(c.status)}">${esc(c.status)}</span></div><small>${esc(c.category||'Kompetisi')} · ${esc(c.slug||'')}</small><div class="chip-row"><span class="chip">Daftar ${fmt(c.registration_starts_at)} → ${fmt(c.registration_ends_at)}</span><span class="chip">Mulai ${fmt(c.starts_at)}</span>${c.juknis_url?'<span class="chip">Juknis</span>':''}${c.kisi_kisi_published?'<span class="chip">Kisi-kisi live</span>':''}</div></div></div><div class="row-actions"><button class="btn btn-ghost btn-sm" data-edit="${c.id}">Edit</button><button class="btn btn-secondary btn-sm" data-config="${c.id}">Config</button><button class="btn btn-primary btn-sm" data-transition="${c.id}">Transisi</button></div></div>`;}).join('')||window.SYKA_EMPTY.render({title:'Belum ada kompetisi',text:'Buat kompetisi pertama untuk workspace ini.'})}</div>`;
    document.getElementById('new-org-comp').onclick=()=>competitionModal(orgId);
    root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>competitionModal(orgId,rows.find(c=>c.id===b.dataset.edit)));
    root.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>configModal(rows.find(c=>c.id===b.dataset.config)));
    root.querySelectorAll('[data-transition]').forEach(b=>b.onclick=()=>transitionModal(rows.find(c=>c.id===b.dataset.transition)));
  }
  function dateField(id,label,value,required=false){
    const p=window.SYKA_UTILS.dateTimeParts(value);
    const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
    const y0=new Date().getFullYear();
    const years=Array.from({length:11},(_,i)=>y0-3+i);
    const maxDay=new Date(p.year,p.month,0).getDate();
    const days=Array.from({length:maxDay},(_,i)=>i+1);
    const hours=Array.from({length:24},(_,i)=>i);
    const minutes=Array.from({length:12},(_,i)=>i*5);
    const options=(items,current,labeler=x=>String(x).padStart(2,'0'))=>items.map(x=>`<option value="${x}" ${Number(x)===Number(current)?'selected':''}>${labeler(x)}</option>`).join('');
    return `<div class="schedule-field" data-schedule-field="${id}">
      <div class="schedule-field-label">${label}${required?' *':''}</div>
      <div class="schedule-trigger-row">
        <button type="button" class="schedule-trigger" data-schedule-open="${id}"><span class="schedule-trigger-icon">▣</span><span data-schedule-date-text></span><span class="schedule-chevron">⌄</span></button>
        <button type="button" class="schedule-trigger time" data-schedule-open="${id}"><span class="schedule-trigger-icon">◷</span><span data-schedule-time-text></span><span class="schedule-chevron">⌄</span></button>
      </div>
      <div class="schedule-popover" data-schedule-popover="${id}">
        <div class="schedule-popover-head"><div><strong>Atur ${label.toLowerCase()}</strong><small>Pilih tanggal dan waktu</small></div></div>
        <div class="schedule-popover-section"><span class="schedule-section-title">Tanggal</span><div class="schedule-select-grid">
          <label>Hari<select data-dt-day="${id}">${options(days,p.day)}</select></label>
          <label>Bulan<select data-dt-month="${id}">${months.map((m,i)=>`<option value="${i+1}" ${i+1===p.month?'selected':''}>${m}</option>`).join('')}</select></label>
          <label>Tahun<select data-dt-year="${id}">${options(years,p.year,x=>String(x))}</select></label>
        </div></div>
        <div class="schedule-popover-section"><span class="schedule-section-title">Waktu</span><div class="schedule-select-grid schedule-time-grid">
          <label>Jam<select data-dt-hour="${id}">${options(hours,p.hour)}</select></label>
          <label>Menit<select data-dt-minute="${id}">${options(minutes,p.minute)}</select></label>
        </div></div>
        <div class="schedule-popover-footer"><span>Waktu lokal perangkat</span><button type="button" class="btn btn-primary btn-sm" data-schedule-done>Selesai</button></div>
      </div>
    </div>`;
  }

  async function competitionModal(orgId,current=null){
    const p=current||{};
    let pendingPosterFile=null;
    let pendingPosterUrl=null;
    let pendingJuknisFile=null;
    window.SYKA_MODAL.open({title:current?'Edit kompetisi':'Buat kompetisi baru',wide:true,html:`<form id="ocf" class="form-card">
      <div class="form-grid-2"><label>Judul *<input id="title" required value="${esc(p.title||'')}"></label><label>Slug *<input id="slug" required value="${esc(p.slug||'')}"></label></div>
      <div class="form-grid-2"><label>Kategori<select id="category"><option ${p.category==='Kompetisi'||!p.category?'selected':''}>Kompetisi</option><option ${p.category==='Olimpiade'?'selected':''}>Olimpiade</option><option ${p.category==='Tryout'?'selected':''}>Tryout</option><option ${p.category==='Lomba Kreatif'?'selected':''}>Lomba Kreatif</option></select></label><label>Visibility<select id="visibility"><option ${p.visibility==='PUBLIC'||!p.visibility?'selected':''}>PUBLIC</option><option ${p.visibility==='UNLISTED'?'selected':''}>UNLISTED</option><option ${p.visibility==='PRIVATE'?'selected':''}>PRIVATE</option></select></label></div>
      <label>Deskripsi singkat<textarea id="short" rows="4" placeholder="Jelaskan kompetisi…">${esc(p.short_description||'')}</textarea></label>
      <div class="form-grid-2"><div class="upload-field-card compact-upload"><div><span class="eyebrow">JUKNIS PDF</span><h3>Panduan resmi</h3><p>File PDF disimpan ke Cloudinary saat kompetisi disimpan.</p></div><div class="upload-preview compact" id="org-juknis-preview">${p.juknis_url?`<div class="upload-file-meta"><strong>Juknis tersimpan</strong><small>${esc(p.juknis_url)}</small></div>`:'<div class="upload-placeholder"><span>PDF</span><strong>Belum ada Juknis</strong><small>PDF • maksimal 15 MB</small></div>'}</div><button type="button" class="btn btn-secondary" id="org-juknis-upload">${p.juknis_url?'Ganti Juknis':'Pilih PDF'}</button><input type="file" id="org-juknis-file" accept="application/pdf" hidden></div><div class="form-card subtle-card"><div class="form-section-title compact"><div><span class="eyebrow">KISI-KISI</span><h3>Publikasi persiapan</h3></div></div><label class="checkline"><input id="kisi-published" type="checkbox" ${p.kisi_kisi_published?'checked':''}> Publikasikan kisi-kisi</label><textarea id="kisi-content" rows="7" placeholder="Materi, topik, kompetensi yang akan diuji…">${esc(p.kisi_kisi_content||'')}</textarea><div class="form-hint">Peserta hanya melihat tombol Kisi-kisi setelah kamu mengaktifkannya.</div></div></div>
      <div class="upload-field-card"><div><span class="eyebrow">POSTER KOMPETISI</span><h3>Upload poster</h3><p>File tetap di perangkat sampai kamu menekan Simpan/Buat Draft.</p></div><div class="upload-preview" id="org-poster-preview">${p.poster_url?`<img src="${esc(p.poster_url)}" alt="Poster"><div class="upload-file-meta"><strong>Poster tersimpan di server</strong><small>Belum ada perubahan lokal</small></div>`:'<div class="upload-placeholder"><span>↑</span><strong>Belum ada poster</strong><small>PNG, JPG, WEBP • maksimal 10 MB</small></div>'}</div><button type="button" class="btn btn-secondary" id="org-poster-upload">${p.poster_url?'Pilih poster baru':'Pilih poster'}</button><input type="file" id="org-poster-file" accept="image/png,image/jpeg,image/webp" hidden></div>
      <div class="form-section-title compact"><div><span class="eyebrow">TIMELINE</span><h2>Jadwal kompetisi</h2><p>Atur tanggal dan waktu dengan picker bergaya scheduler.</p></div></div>
      <div class="form-grid-2">${dateField('rs','Pendaftaran mulai',p.registration_starts_at,true)}${dateField('re','Pendaftaran berakhir',p.registration_ends_at,true)}</div>
      <div class="form-grid-2">${dateField('start','Kompetisi mulai',p.starts_at,true)}${dateField('end','Kompetisi berakhir',p.ends_at,true)}</div>
      ${dateField('ann','Pengumuman',p.announcement_at,false)}
      <div id="oc-feedback"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Batal</button><button class="btn btn-primary" id="org-comp-submit">${current?'Simpan perubahan':'Buat sebagai DRAFT'}</button></div>
    </form>`,onOpen:b=>{
      window.SYKA_UTILS.bindSchedulePickers(b);
      const fileInput=b.querySelector('#org-poster-file');
      const uploadBtn=b.querySelector('#org-poster-upload');
      const preview=b.querySelector('#org-poster-preview');
      uploadBtn.onclick=()=>fileInput.click();
      fileInput.onchange=()=>{
        const file=fileInput.files?.[0];
        if(!file)return;
        if(file.size>10000000){fileInput.value='';window.SYKA_TOAST.show('Ukuran poster maksimal 10 MB.','error');return;}
        if(!['image/png','image/jpeg','image/webp'].includes(file.type)){fileInput.value='';window.SYKA_TOAST.show('Gunakan PNG, JPG, atau WEBP.','error');return;}
        pendingPosterFile=file;
        if(pendingPosterUrl)URL.revokeObjectURL(pendingPosterUrl);
        pendingPosterUrl=URL.createObjectURL(file);
        preview.innerHTML=`<img src="${pendingPosterUrl}" alt="Poster baru"><div class="upload-file-meta"><strong>${esc(file.name)}</strong><small>Siap diupload saat disimpan · belum dikirim ke server</small></div>`;
        uploadBtn.textContent='Ganti poster';
      };
      const juknisInput=b.querySelector('#org-juknis-file');
      const juknisBtn=b.querySelector('#org-juknis-upload');
      juknisBtn.onclick=()=>juknisInput.click();
      juknisInput.onchange=()=>{const f=juknisInput.files?.[0];if(!f)return;if(f.size>15000000){juknisInput.value='';window.SYKA_TOAST.show('Ukuran PDF maksimal 15 MB.','error');return;}pendingJuknisFile=f;b.querySelector('#org-juknis-preview').innerHTML=`<div class="upload-file-meta"><strong>${esc(f.name)}</strong><small>Siap diupload saat disimpan · belum dikirim ke server</small></div>`;juknisBtn.textContent='Ganti PDF';};
      b.querySelector('#ocf').onsubmit=async e=>{
        e.preventDefault();
        const btn=b.querySelector('#org-comp-submit');
        const feedback=b.querySelector('#oc-feedback');
        btn.disabled=true;
        try{
          let media=p.poster_url?{secure_url:p.poster_url,public_id:p.poster_public_id||'',width:p.poster_width||null,height:p.poster_height||null,version:p.poster_version||'',resource_type:p.poster_resource_type||'image'}:null;
          if(pendingPosterFile){btn.innerHTML='<span class="spinner"></span> Mengunggah poster…';media=await window.SYKA_CLOUDINARY.uploadFile(pendingPosterFile,{folder:'sykabelajar/competitions/posters',maxFileSize:10000000});}
          let juknisUrl=p.juknis_url||null;let juknisPublicId=p.juknis_public_id||null;
          if(pendingJuknisFile){btn.innerHTML='<span class="spinner"></span> Mengunggah Juknis…';const doc=await window.SYKA_CLOUDINARY.uploadDocumentFile(pendingJuknisFile,{folder:'sykabelajar/competitions/juknis',maxFileSize:15000000});juknisUrl=doc.secure_url;juknisPublicId=doc.public_id||null;}
          btn.innerHTML='<span class="spinner"></span> Menyimpan…';
          const payload={organizer_id:orgId,title:b.querySelector('#title').value.trim(),slug:b.querySelector('#slug').value.trim().toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-+|-+$/g,''),category:b.querySelector('#category').value.trim()||'Kompetisi',short_description:b.querySelector('#short').value.trim()||null,visibility:b.querySelector('#visibility').value,poster_url:media?.secure_url||null,poster_public_id:media?.public_id||null,poster_width:media?.width||null,poster_height:media?.height||null,poster_version:media?.version||null,poster_resource_type:media?.resource_type||'image',juknis_url:juknisUrl,juknis_public_id:juknisPublicId,kisi_kisi_published:b.querySelector('#kisi-published').checked,kisi_kisi_content:b.querySelector('#kisi-content').value.trim()||null,registration_starts_at:window.SYKA_UTILS.readDateTimeField('rs',b),registration_ends_at:window.SYKA_UTILS.readDateTimeField('re',b),starts_at:window.SYKA_UTILS.readDateTimeField('start',b),ends_at:window.SYKA_UTILS.readDateTimeField('end',b),announcement_at:window.SYKA_UTILS.readDateTimeField('ann',b)};
          await svc().saveCompetition(payload,current?.id||null);
          if(pendingPosterUrl)URL.revokeObjectURL(pendingPosterUrl);
          window.SYKA_MODAL.close();window.SYKA_TOAST.show(current?'Kompetisi diperbarui.':'Kompetisi dibuat sebagai DRAFT.','success');window.SYKA_ROUTER.refresh();
        }catch(error){btn.disabled=false;btn.textContent=current?'Simpan perubahan':'Buat sebagai DRAFT';feedback.innerHTML=`<div class="inline-error">${esc(error.message||'Gagal menyimpan kompetisi.')}</div>`;}
      };
    }});
  }

  function transitionModal(c){const choices=transitions[c.status]||[];if(!choices.length){window.SYKA_TOAST.show(`Tidak ada transisi valid dari ${c.status}.`,'warning');return;}window.SYKA_MODAL.open({title:'Ubah status kompetisi',html:`<div class="transition-current"><span>STATUS SAAT INI</span><strong>${esc(c.status)}</strong></div><form id="otf" class="form-card"><label>Status tujuan<select id="target">${choices.map(s=>`<option>${s}</option>`).join('')}</select></label><label>Alasan<textarea id="reason" placeholder="Mengapa status ini diubah?"></textarea></label><button class="btn btn-primary btn-block">Terapkan</button><div class="form-hint">Backend akan memvalidasi lifecycle dan mencatat audit.</div></form>`,onOpen:b=>b.querySelector('#otf').onsubmit=async e=>{e.preventDefault();try{await svc().transitionCompetition(c.id,b.querySelector('#target').value,b.querySelector('#reason').value.trim()||null);window.SYKA_MODAL.close();window.SYKA_TOAST.show('Status kompetisi diperbarui.','success');window.SYKA_ROUTER.refresh();}catch(error){b.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}}});}
  function configModal(c){window.SYKA_MODAL.open({title:`Config · ${c.title}`,html:`<div class="config-grid"><button class="config-card" id="lvl"><span>◫</span><strong>Jenjang</strong><small>Grade, points, level kompetisi.</small></button><button class="config-card" id="rules"><span>◌</span><strong>Registrasi</strong><small>Eligibility, twibbon, quota.</small></button><button class="config-card" id="reward"><span>✦</span><strong>Reward</strong><small>Juara, poin, emblem.</small></button></div>`,onOpen:b=>{b.querySelector('#lvl').onclick=()=>levelModal(c.id);b.querySelector('#rules').onclick=()=>rulesModal(c.id);b.querySelector('#reward').onclick=()=>rewardModal(c.id);}});}
  async function levelModal(id){
    const rows=await svc().listLevels(id);
    const html=rows.length?rows.map(r=>`<div class="list-card"><strong>${esc(r.label)}</strong><small>${esc(r.code)} · ${(r.allowed_grades||[]).join(', ')}</small><span>${r.points} pts</span></div>`).join(''):'<div class="empty-inline">Belum ada level.</div>';
    window.SYKA_MODAL.open({title:'Jenjang kompetisi',html:`<div class="modal-toolbar"><button class="btn btn-primary btn-sm" id="new-level">+ Level</button></div><div class="stack-list">${html}</div>`,onOpen:b=>{
      b.querySelector('#new-level').onclick=()=>window.SYKA_MODAL.open({title:'Tambah level',html:`<form id="lf" class="form-card"><label>Kode<input id="code" required></label><label>Label<input id="label" required></label><label>Allowed grades<textarea id="grades">SD6</textarea></label><label>Points<input id="points" type="number" value="0"></label><button class="btn btn-primary">Simpan</button></form>`,onOpen:x=>{
        x.querySelector('#lf').onsubmit=async e=>{e.preventDefault();try{await svc().saveLevel({competition_id:id,code:x.querySelector('#code').value.trim(),label:x.querySelector('#label').value.trim(),allowed_grades:x.querySelector('#grades').value.split(/[,\n]+/).map(v=>v.trim()).filter(Boolean),points:Number(x.querySelector('#points').value||0),config:{}});window.SYKA_MODAL.close();window.SYKA_TOAST.show('Level tersimpan.','success');levelModal(id);}catch(error){x.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}};
      }});
    }});
  }
  async function rulesModal(id){
    const r=await svc().getRegistrationRules(id)||{};
    const compRows=await svc().listCompetitionsAdmin({limit:200});
    const comp=compRows.find(x=>x.id===id);
    const orgPlan=await svc().listActiveOrganizerPlan(comp?.organizer_id).catch(()=>null);
    const ent=await svc().listEntitlements().catch(()=>[]);
    const autoAvailable=!!ent.find(e=>e.plan_code===orgPlan?.plan_code && e.capability==='auto_registration_approval' && (e.limit_value==null || Number(e.limit_value)>0));
    window.SYKA_MODAL.open({title:'Aturan pendaftaran',wide:true,html:`<form id="rf" class="form-card"><div class="form-section-title compact"><div><span class="eyebrow">ELIGIBILITY</span><h3>Siapa yang boleh mendaftar?</h3></div></div><label>Allowed grades<textarea id="grades" placeholder="SD6, SMP7, SMP8, SMA10">${esc((r.allowed_grades||[]).join(', '))}</textarea></label><div class="form-grid-2"><label class="checkline"><input id="twibbon" type="checkbox" ${r.require_twibbon?'checked':''}> Wajib twibbon</label><label class="checkline"><input id="social" type="checkbox" ${r.require_social_proof?'checked':''}> Wajib social proof</label></div><div class="form-grid-2"><label>Maximum peserta<input id="max" type="number" min="1" value="${r.max_participants||''}" placeholder="Tanpa batas"></label><label>Mode persetujuan<select id="approval"><option value="MANUAL" ${r.approval_mode!=='AUTO'?'selected':''}>Manual — organizer review</option><option value="AUTO" ${r.approval_mode==='AUTO'?'selected':''} ${autoAvailable?'':'disabled'}>Otomatis — sesuai entitlement</option></select></label></div><div class="plan-note ${autoAvailable?'':'warning'}">${autoAvailable?'Paket aktif mendukung auto approval. Server tetap menjadi sumber keputusan.':'Auto approval belum tersedia pada paket workspace ini. Upgrade paket untuk mengaktifkannya.'}</div><button class="btn btn-primary">Simpan aturan</button><div id="rf-feedback"></div></form>`,onOpen:b=>b.querySelector('#rf').onsubmit=async e=>{e.preventDefault();try{const approval=b.querySelector('#approval').value;await svc().saveRegistrationRules({allowed_grades:b.querySelector('#grades').value.split(/[,\n]+/).map(v=>v.trim()).filter(Boolean),require_twibbon:b.querySelector('#twibbon').checked,require_social_proof:b.querySelector('#social').checked,max_participants:b.querySelector('#max').value?Number(b.querySelector('#max').value):null,approval_mode:approval,config:{}},id);window.SYKA_MODAL.close();window.SYKA_TOAST.show('Aturan pendaftaran tersimpan.','success');}catch(error){b.querySelector('#rf-feedback').innerHTML=`<div class="inline-error">${esc(error.message)}</div>`;}}});
  }
  async function rewardModal(id){
    const rows=await svc().listRewards(id);
    const html=rows.length?rows.map(r=>`<div class="list-card"><strong>${esc(r.rank_code)}</strong><small>${esc(r.title||'Reward')}</small><span>${r.points} pts</span></div>`).join(''):'<div class="empty-inline">Belum ada reward.</div>';
    window.SYKA_MODAL.open({title:'Reward kompetisi',html:`<div class="modal-toolbar"><button class="btn btn-primary btn-sm" id="new-reward">+ Reward</button></div><div class="stack-list">${html}</div>`,onOpen:b=>{
      b.querySelector('#new-reward').onclick=()=>window.SYKA_MODAL.open({title:'Tambah reward',html:`<form id="rew" class="form-card"><label>Rank code<input id="rank" required></label><label>Title<input id="title" required></label><label>Points<input id="points" type="number" value="0"></label><label>Emblem<input id="emblem"></label><label class="checkline"><input id="cert" type="checkbox" checked> Certificate enabled</label><button class="btn btn-primary">Simpan</button></form>`,onOpen:x=>{
        x.querySelector('#rew').onsubmit=async e=>{e.preventDefault();try{await svc().saveReward({competition_id:id,rank_code:x.querySelector('#rank').value.trim(),title:x.querySelector('#title').value.trim(),points:Number(x.querySelector('#points').value||0),emblem_name:x.querySelector('#emblem').value.trim()||null,certificate_enabled:x.querySelector('#cert').checked,config:{}});window.SYKA_MODAL.close();window.SYKA_TOAST.show('Reward tersimpan.','success');rewardModal(id);}catch(error){x.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}};
      }});
    }});
  }
  async function participants(root,orgId){
    const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});
    let rows=[];
    for(const c of comps){const list=await svc().listRegistrations({competitionId:c.id});rows.push(...list);}
    root.innerHTML=`<div class="toolbar"><div><span class="eyebrow">REGISTRATION REVIEW</span><h2>Peserta</h2><p>Lihat profil peserta, social proof, dan status twibbon. Gambar twibbon hasil peserta tidak disimpan server.</p></div><div class="filter-line"><select id="reg-status" class="compact-select"><option value="">Semua</option><option>PENDING</option><option>ACTIVE</option><option>REJECTED</option></select></div></div><div class="participant-review-grid-v47" id="participants-table">${rows.map(r=>`<article class="participant-card-v47" data-status="${esc(r.status)}"><div class="participant-card-head-v47"><div class="row-main"><div class="avatar-mini">${r.profiles?.avatar_url?`<img src="${esc(r.profiles.avatar_url)}" alt="">`:esc(window.SYKA_UTILS.initials(r.profiles?.full_name||r.user_id))}</div><div><div class="row-title"><strong>${esc(r.profiles?.full_name||r.user_id)}</strong><span class="status-pill ${window.SYKA_UTILS.statusClass(r.status)}">${esc(r.status)}</span></div><small>@${esc(r.profiles?.username||'—')} · ${esc(r.profiles?.grade||'—')} · ${esc(r.competitions?.title||'')}</small></div></div><button class="btn btn-ghost btn-sm" data-participant-detail="${r.id}">Detail</button></div><div class="participant-proof-grid-v47"><div><span>Twibbon</span><strong>${r.metadata?.twibbon_completed?'✓ Selesai':'Tidak diwajibkan / belum'}</strong></div><div><span>Social proof</span>${r.social_proof_url?`<a href="${esc(r.social_proof_url)}" target="_blank" rel="noopener">Buka postingan ↗</a>`:'<strong>—</strong>'}</div><div><span>Dikirim</span><strong>${fmt(r.submitted_at)}</strong></div></div><div class="row-actions participant-actions-v47">${r.status==='PENDING'?`<button class="btn btn-primary btn-sm" data-approve="${r.id}">Approve</button><button class="btn btn-danger-outline btn-sm" data-reject="${r.id}">Reject</button>`:''}${r.status==='ACTIVE'?'<span class="status-pill status-success">Peserta aktif</span>':''}</div></article>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada peserta',text:'Registration akan masuk saat peserta mengirim pendaftaran.'})}</div>`;
    document.getElementById('reg-status').onchange=e=>root.querySelectorAll('#participants-table .participant-card-v47').forEach(r=>r.style.display=!e.target.value||r.dataset.status===e.target.value?'grid':'none');
    root.querySelectorAll('[data-participant-detail]').forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.participantDetail);if(!r)return;window.SYKA_MODAL.open({title:'Detail peserta',wide:true,html:`<div class="participant-detail-modal-v47"><div class="admin-user-detail-head"><div class="avatar-xl-v47">${r.profiles?.avatar_url?`<img src="${esc(r.profiles.avatar_url)}" alt="">`:esc(window.SYKA_UTILS.initials(r.profiles?.full_name||r.user_id))}</div><div><span class="eyebrow">REGISTRATION</span><h2>${esc(r.profiles?.full_name||r.user_id)}</h2><p>@${esc(r.profiles?.username||'—')} · ${esc(r.status)}</p></div></div><div class="detail-list-v47"><div><span>Kompetisi</span><strong>${esc(r.competitions?.title||'—')}</strong></div><div><span>Jenjang / kelas</span><strong>${esc(r.profiles?.grade||'—')}</strong></div><div><span>Sekolah</span><strong>${esc(r.profiles?.institution||'—')}</strong></div><div><span>Twibbon</span><strong>${r.metadata?.twibbon_completed?'Selesai':'Tidak ada bukti'}</strong></div><div><span>Social proof</span><strong>${r.social_proof_url?`<a href="${esc(r.social_proof_url)}" target="_blank" rel="noopener">${esc(r.social_proof_url)}</a>`:'—'}</strong></div><div><span>Waktu kirim</span><strong>${fmt(r.submitted_at)}</strong></div></div></div>`});});
    root.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>review(b.dataset.approve,'APPROVED'));
    root.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>rejectModal(b.dataset.reject));
  }

  async function review(id,decision,reason=null){try{await svc().reviewRegistration(id,decision,reason);window.SYKA_TOAST.show('Status peserta diperbarui.','success');window.SYKA_ROUTER.refresh();}catch(error){window.SYKA_TOAST.show(error.message,'error');}}
  function rejectModal(id){window.SYKA_MODAL.open({title:'Reject peserta',html:`<form id="rej" class="form-card"><label>Alasan penolakan *<textarea id="reason" required></textarea></label><button class="btn btn-danger">Tolak peserta</button></form>`,onOpen:b=>b.querySelector('#rej').onsubmit=async e=>{e.preventDefault();await review(id,'REJECTED',b.querySelector('#reason').value.trim());window.SYKA_MODAL.close();}});}
  async function questions(root,orgId){
    const [banks,comps]=await Promise.all([svc().listQuestionBanks({organizerId:orgId}),svc().listCompetitionsAdmin({organizerId:orgId,limit:200})]);
    let selectedBank=banks[0]?.id||'';
    const render=async()=>{
      const bank=banks.find(x=>x.id===selectedBank);
      const list=selectedBank?await svc().listQuestions({bankId:selectedBank}):[];
      root.innerHTML=`<div class="toolbar"><div><span class="eyebrow">QUESTION ENGINE</span><h2>Soal kompetisi</h2><p>Siapkan bank soal, buat pertanyaan, dan publikasi hanya untuk tahap LIVE.</p></div><div class="toolbar-actions"><button class="btn btn-secondary" id="import-questions">Import JSON/CSV</button><button class="btn btn-primary" id="new-question">+ Soal</button></div></div><section class="question-workspace-v47"><aside class="question-bank-sidebar-v47"><div class="sidebar-head"><strong>Bank soal</strong><button class="btn btn-ghost btn-xs" id="new-bank">+ Bank</button></div><div class="question-bank-list">${banks.map(b=>`<button class="question-bank-item ${b.id===selectedBank?'active':''}" data-bank="${b.id}"><strong>${esc(b.name)}</strong><small>${esc(b.status)} · ${esc(b.description||'')}</small></button>`).join('')||'<div class="empty-inline">Belum ada bank soal.</div>'}</div></aside><section class="question-editor-v47"><div class="question-editor-head"><div><span class="eyebrow">${esc(bank?.name||'Pilih bank soal')}</span><h3>${esc(bank?.description||'Buat bank soal untuk kompetisi.')}</h3></div><span class="status-pill ${window.SYKA_UTILS.statusClass(bank?.status||'DRAFT')}">${esc(bank?.status||'DRAFT')}</span></div><div class="question-list-v47">${list.map((q,i)=>`<article class="question-row-v47"><div class="question-number">${i+1}</div><div class="question-copy"><div class="question-meta"><span>${esc(q.type)}</span><span>${Number(q.points||0)} pts</span><span>${q.required?'Wajib':'Opsional'}</span><span>${esc(q.status)}</span></div><strong>${esc(q.prompt)}</strong><small>Urutan ${q.display_order}</small></div></article>`).join('')||'<div class="empty-inline">Belum ada soal di bank ini.</div>'}</div></section></section>`;
      root.querySelectorAll('[data-bank]').forEach(b=>b.onclick=()=>{selectedBank=b.dataset.bank;render();});
      document.getElementById('new-bank').onclick=()=>window.SYKA_MODAL.open({title:'Bank soal baru',html:`<form id="bf" class="form-card"><label>Nama bank<input id="name" required></label><label>Deskripsi<textarea id="desc"></textarea></label><label>Status<select id="status"><option>DRAFT</option><option>REVIEW</option><option>PUBLISHED</option></select></label><button class="btn btn-primary">Simpan</button></form>`,onOpen:b=>b.querySelector('#bf').onsubmit=async e=>{e.preventDefault();try{const bank=await svc().saveQuestionBank({organizer_id:orgId,name:b.querySelector('#name').value.trim(),description:b.querySelector('#desc').value.trim()||null,status:b.querySelector('#status').value,config:{}});window.SYKA_MODAL.close();banks.push(bank);selectedBank=bank.id;render();}catch(error){b.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}}});
      document.getElementById('new-question').onclick=()=>questionModal(selectedBank,comps);
      document.getElementById('import-questions').onclick=()=>importQuestionModal(selectedBank);
    };
    await render();
  }
  function questionModal(bankId,comps){
    window.SYKA_MODAL.open({title:'Tambah soal',wide:true,html:`<form id="qf" class="form-card"><div class="form-grid-2"><label>Kompetisi<select id="competition"><option value="">Tidak terikat</option>${comps.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label><label>Jenis<select id="type"><option value="multiple_choice">Pilihan ganda</option><option value="multiple_checkbox">Multiple checkbox</option><option value="true_false">Benar / Salah</option><option value="short_answer">Isian singkat</option><option value="essay">Essay</option><option value="file_upload">Upload file</option></select></label></div><label>Pertanyaan *<textarea id="prompt" rows="5" required></textarea></label><div class="form-grid-2"><label>Poin<input id="points" type="number" min="0" step="0.5" value="1"></label><label>Urutan<input id="order" type="number" min="0" value="0"></label></div><div id="options-zone"><div class="option-builder-v47"><span class="eyebrow">OPTIONS</span><div id="options-list"></div><button type="button" class="btn btn-secondary btn-sm" id="add-option">+ Opsi</button></div></div><label class="checkline"><input id="required" type="checkbox" checked> Wajib dijawab</label><button class="btn btn-primary">Simpan soal</button><div id="qf-feedback"></div></form>`,onOpen:b=>{
      const type=b.querySelector('#type'), list=b.querySelector('#options-list');
      function paintOptions(){if(!['multiple_choice','multiple_checkbox','true_false'].includes(type.value)){b.querySelector('#options-zone').innerHTML='';return;}if(!list.children.length){['A','B','C','D'].forEach((v)=>add(v,v=== 'A'));} }
      function add(label='',correct=false){const row=document.createElement('div');row.className='option-row-v47';row.innerHTML=`<input data-label value="${esc(label)}" placeholder="Label"><input data-value value="${esc(label)}" placeholder="Value"><label><input data-correct type="checkbox" ${correct?'checked':''}> Benar</label><button type="button" class="btn btn-ghost btn-xs" data-remove>×</button>`;row.querySelector('[data-remove]').onclick=()=>row.remove();list.appendChild(row);}
      b.querySelector('#add-option').onclick=()=>add('');type.onchange=paintOptions;paintOptions();
      b.querySelector('#qf').onsubmit=async e=>{e.preventDefault();try{const options=[...b.querySelectorAll('.option-row-v47')].map((r,i)=>({label:r.querySelector('[data-label]').value.trim(),value:r.querySelector('[data-value]').value.trim(),is_correct:r.querySelector('[data-correct]').checked,display_order:i})).filter(x=>x.label);const q=await svc().saveQuestion({question_bank_id:bankId,competition_id:b.querySelector('#competition').value||null,type:type.value,prompt:b.querySelector('#prompt').value.trim(),points:Number(b.querySelector('#points').value||0),required:b.querySelector('#required').checked,display_order:Number(b.querySelector('#order').value||0),config:{}},null);if(options.length)await svc().replaceOptions(q.id,options);window.SYKA_MODAL.close();window.SYKA_TOAST.show('Soal tersimpan.','success');window.SYKA_ROUTER.refresh();}catch(error){b.querySelector('#qf-feedback').innerHTML=`<div class="inline-error">${esc(error.message)}</div>`;}};
    }});
  }
  function importQuestionModal(bankId){window.SYKA_MODAL.open({title:'Import soal',wide:true,html:`<div class="form-card"><p>Gunakan CSV: <code>type,prompt,points,required,display_order</code> atau JSON array objek soal.</p><input type="file" id="question-file" accept=".csv,.json,text/csv,application/json"><div id="import-feedback"></div><div class="form-actions"><button class="btn btn-ghost" data-close>Batal</button><button class="btn btn-primary" id="run-import">Import</button></div></div>`,onOpen:b=>{b.querySelector('[data-close]').onclick=()=>window.SYKA_MODAL.close();b.querySelector('#run-import').onclick=async()=>{const f=b.querySelector('#question-file').files?.[0];if(!f){b.querySelector('#import-feedback').innerHTML='<div class="inline-error">Pilih file terlebih dahulu.</div>';return;}try{const txt=await f.text();let rows=[];if(f.name.toLowerCase().endsWith('.json'))rows=JSON.parse(txt);else{const lines=txt.split(/\r?\n/).filter(Boolean);const headers=lines.shift().split(',').map(x=>x.trim());rows=lines.map(line=>{const vals=line.split(',');return Object.fromEntries(headers.map((h,i)=>[h,(vals[i]||'').trim()]));});}for(const [i,row] of rows.entries()){const q=await svc().saveQuestion({question_bank_id:bankId,competition_id:row.competition_id||null,type:row.type||'multiple_choice',prompt:row.prompt||'',points:Number(row.points||1),required:row.required!=='false',display_order:Number(row.display_order||i),config:{}},null);if(Array.isArray(row.options))await svc().replaceOptions(q.id,row.options);}window.SYKA_MODAL.close();window.SYKA_TOAST.show(`${rows.length} soal berhasil diimport.`,'success');window.SYKA_ROUTER.refresh();}catch(error){b.querySelector('#import-feedback').innerHTML=`<div class="inline-error">${esc(error.message||'Import gagal.')}</div>`;}};}});}
  async function grading(root,orgId){const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});let rows=[];for(const c of comps)rows.push(...await svc().listAttempts({competitionId:c.id}));root.innerHTML=`<div class="toolbar"><div><h2>Grading</h2><p>Auto/manual grading dan finalize score.</p></div><select class="compact-select" id="grading-filter"><option value="">Semua status</option><option>SUBMITTED</option><option>GRADING</option><option>FINALIZED</option></select></div><div class="data-table" id="grading-table">${rows.map(a=>`<div class="data-row" data-status="${esc(a.status)}"><div><strong>${esc(a.profiles?.full_name||a.participant_id)}</strong><small>${esc(a.competitions?.title||'')} · ${esc(a.status)} · Score ${a.score??0}</small></div><div class="row-actions">${a.status!=='FINALIZED'?`<button class="btn btn-ghost btn-sm" data-grade="${a.id}">Grade</button><button class="btn btn-primary btn-sm" data-final="${a.id}">Finalize</button>`:'<span class="status-pill status-success">FINALIZED</span>'}</div></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada attempt',text:'Submission peserta akan muncul ketika attempt engine aktif.'})}</div>`;document.getElementById('grading-filter').onchange=e=>root.querySelectorAll('[data-status]').forEach(r=>r.style.display=!e.target.value||r.dataset.status===e.target.value?'flex':'none');root.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>gradeModal(b.dataset.grade));root.querySelectorAll('[data-final]').forEach(b=>b.onclick=()=>finalizeModal(b.dataset.final));}
  async function gradeModal(id){const items=await svc().listGradingItems(id);window.SYKA_MODAL.open({title:'Grading attempt',wide:true,html:`<form id="gf" class="form-card">${items.map((i,n)=>`<div class="grade-item"><div><strong>Item ${n+1}</strong><small>Question ${esc(i.question_id||'')}</small></div><div class="form-grid-2"><label>Score<input type="number" step="0.01" data-score="${i.id}" value="${i.score??0}"></label><label>Feedback<input data-feedback="${i.id}" value="${esc(i.feedback||'')}"></label></div></div>`).join('')||'<div class="empty-inline">Belum ada manual grading item.</div>'}<button class="btn btn-primary">Simpan grading</button></form>`,onOpen:b=>b.querySelector('#gf').onsubmit=async e=>{e.preventDefault();try{for(const i of items){await svc().saveGrade({attempt_id:id,question_id:i.question_id,grader_id:window.SYKA_STATE.getState().auth.user.id,score:Number(b.querySelector(`[data-score="${i.id}"]`).value||0),feedback:b.querySelector(`[data-feedback="${i.id}"]`).value||null},i.id);}window.SYKA_MODAL.close();window.SYKA_TOAST.show('Grading tersimpan.','success');window.SYKA_ROUTER.refresh();}catch(error){b.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}}});}
  function finalizeModal(id){window.SYKA_MODAL.open({title:'Finalize result',html:`<form id="ff" class="form-card"><label>Score final *<input id="score" type="number" step="0.01" min="0" required></label><div class="form-hint">Finalization adalah langkah one-way pada core flow dan harus diaudit.</div><button class="btn btn-primary">Finalize result</button></form>`,onOpen:b=>b.querySelector('#ff').onsubmit=async e=>{e.preventDefault();try{await svc().finalizeAttempt(id,Number(b.querySelector('#score').value||0));window.SYKA_MODAL.close();window.SYKA_TOAST.show('Result finalized.','success');window.SYKA_ROUTER.refresh();}catch(error){b.insertAdjacentHTML('beforeend',`<div class="inline-error">${esc(error.message)}</div>`);}}});}
  async function results(root,orgId){const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});let rows=[];for(const c of comps)rows.push(...await svc().listAttempts({competitionId:c.id,status:'FINALIZED'}));root.innerHTML=`<div class="toolbar"><div><h2>Hasil</h2><p>Hasil final dari semua kompetisi organizer.</p></div></div><div class="data-table">${rows.map(a=>`<div class="data-row"><div><strong>${esc(a.profiles?.full_name||a.participant_id)}</strong><small>${esc(a.competitions?.title||'')} · ${fmt(a.finalized_at)}</small></div><strong>${Number(a.score||0).toLocaleString('id-ID')} pts</strong></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada hasil',text:'Finalize attempt dari tab Grading untuk mengisi hasil.'})}</div>`;}
  async function awards(root,orgId){const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});let rows=[];for(const c of comps)rows.push(...await svc().listAwards({competitionId:c.id}));root.innerHTML=`<div class="toolbar"><div><h2>Awards</h2><p>Achievement, emblem, dan points dari result event.</p></div></div><div class="data-table">${rows.map(a=>`<div class="data-row"><div><strong>${esc(a.title)}</strong><small>${esc(a.rank_code||'PARTICIPANT')} · ${esc(a.competition_id||'')}</small></div><span class="chip">${Number(a.points||0)} pts</span></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada awards',text:'Award event akan muncul setelah result publication backend.'})}</div>`;}
  async function certificates(root,orgId){const comps=await svc().listCompetitionsAdmin({organizerId:orgId,limit:200});let rows=[];for(const c of comps)rows.push(...await svc().listCertificates({competitionId:c.id}));root.innerHTML=`<div class="toolbar"><div><h2>Sertifikat</h2><p>DRAFT → GENERATED → REVIEW → APPROVED → PUBLISHED → REVOKED.</p></div></div><div class="data-table">${rows.map(c=>`<div class="data-row"><div><strong>${esc(c.user_id)}</strong><small>${esc(c.competition_id||'')} · revisi ${c.current_revision}</small></div><span class="status-pill ${window.SYKA_UTILS.statusClass(c.status)}">${esc(c.status)}</span></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada certificate',text:'Certificate akan dibuat setelah award event.'})}</div>`;}
  async function twibbon(root,orgId){
    const rows=await svc().listTwibbonTemplates({organizerId:orgId});
    root.innerHTML=`<div class="toolbar"><div><span class="eyebrow">MEDIA</span><h2>Twibbon</h2><p>Template twibbon disimpan di Cloudinary. URL tidak perlu dimasukkan manual.</p></div><button class="btn btn-primary" id="new-tw">+ Template</button></div><div class="data-table">${rows.map(t=>`<div class="data-row"><div class="row-main"><div class="media-thumb">${t.image_url?`<img src="${esc(window.SYKA_UTILS.cloudinaryTransform(t.image_url,{width:120,height:120,crop:'fill'}))}" alt="">`:'✦'}</div><div><strong>${esc(t.name)}</strong><small>${esc(t.competition_id||'Global')} · ${t.is_required?'Wajib':'Opsional'}</small></div></div><div class="chip-row"><span class="chip">${t.is_active?'Aktif':'Nonaktif'}</span></div></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada template',text:'Tambahkan template twibbon untuk kompetisi.'})}</div>`;
    document.getElementById('new-tw').onclick=()=>window.SYKA_MODAL.open({title:'Twibbon template',wide:true,html:`<form id="twf" class="form-card"><label>Competition ID<input id="cid" placeholder="UUID competition"></label><label>Nama template *<input id="name" required></label><div class="upload-field-card"><div><span class="eyebrow">TWIBBON</span><h3>Upload gambar template</h3><p>Rasio 1:1. File dikirim langsung ke Cloudinary.</p></div><div class="upload-preview" id="tw-preview"><div class="upload-placeholder"><span>↑</span><strong>Belum ada template</strong><small>PNG, JPG, WEBP • maksimal 10 MB</small></div></div><button type="button" class="btn btn-secondary" id="tw-upload">Pilih gambar</button><input type="hidden" id="url"><input type="hidden" id="pid"><input type="hidden" id="w"><input type="hidden" id="h"><input type="hidden" id="v"><input type="hidden" id="r"></div><label class="checkline"><input id="req" type="checkbox"> Wajib</label><div id="tw-feedback"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-close>Batal</button><button class="btn btn-primary">Simpan</button></div></form>`,onOpen:b=>{let info=null;b.querySelector('[data-close]').onclick=()=>window.SYKA_MODAL.close();b.querySelector('#tw-upload').onclick=async()=>{try{info=await window.SYKA_CLOUDINARY.openTwibbonWidget();b.querySelector('#url').value=info.secure_url||'';b.querySelector('#pid').value=info.public_id||'';b.querySelector('#w').value=info.width||'';b.querySelector('#h').value=info.height||'';b.querySelector('#v').value=info.version||'';b.querySelector('#r').value=info.resource_type||'image';b.querySelector('#tw-preview').innerHTML=`<img src="${esc(info.secure_url)}" alt="Twibbon"><div class="upload-file-meta"><strong>${esc(info.original_filename||'Twibbon')}</strong><small>Cloudinary</small></div>`;b.querySelector('#tw-upload').textContent='Ganti gambar';}catch(e){b.querySelector('#tw-feedback').innerHTML=`<div class="inline-error">${esc(e.message||'Upload gagal.')}</div>`;}};b.querySelector('#twf').onsubmit=async e=>{e.preventDefault();try{if(!b.querySelector('#url').value.trim())throw new Error('Upload template terlebih dahulu.');await svc().saveTwibbonTemplate({organizer_id:orgId,competition_id:b.querySelector('#cid').value.trim()||null,name:b.querySelector('#name').value.trim(),image_url:b.querySelector('#url').value.trim(),public_id:b.querySelector('#pid').value.trim()||null,is_required:b.querySelector('#req').checked,is_active:true,config:{width:Number(b.querySelector('#w').value)||null,height:Number(b.querySelector('#h').value)||null,version:b.querySelector('#v').value||null,resource_type:b.querySelector('#r').value||'image'}});window.SYKA_MODAL.close();window.SYKA_TOAST.show('Template twibbon tersimpan.','success');window.SYKA_ROUTER.refresh();}catch(error){b.querySelector('#tw-feedback').innerHTML=`<div class="inline-error">${esc(error.message||'Gagal menyimpan template.')}</div>`;}};}});
  }

  async function notifications(root){const a=window.SYKA_STATE.getState().auth;const rows=await window.SYKA_NOTIFICATION_SERVICE.list(a.user.id);root.innerHTML=`<div class="toolbar"><div><h2>Notifikasi</h2><p>Event dan update yang dikirim ke user organizer.</p></div></div><div class="data-table">${rows.map(n=>`<div class="data-row"><div><strong>${esc(n.title||'Notifikasi')}</strong><small>${esc(n.body||'')} · ${fmt(n.created_at)}</small></div><span class="status-pill ${n.read_at?'status-neutral':'status-success'}">${n.read_at?'Sudah dibaca':'Baru'}</span></div>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada notifikasi',text:'Event backend akan masuk di sini.'})}</div>`;}
  async function plan(root,orgId){
    const [active,entitlements,catalog]=await Promise.all([svc().listActiveOrganizerPlan(orgId),svc().listEntitlements(),svc().listPlanCatalog()]);
    const current=active?.plan_code||'FREE';
    const meta=catalog.find(x=>x.plan_code===current);
    root.innerHTML=`<section class="plan-usage-header-v46"><div><span class="eyebrow">PLAN & USAGE</span><h2>${esc(meta?.name||current)}</h2><p>${active?`Aktif sejak ${fmt(active.starts_at)}.`:'Belum ada paket aktif.'} Capability dan quota berasal dari backend.</p></div><div class="plan-usage-actions"><span class="plan-badge ${current.toLowerCase()}">${esc(meta?.badge||current)}</span><button class="btn btn-secondary btn-sm" id="change-plan">Lihat opsi upgrade</button></div></section><section class="panel-card"><div class="panel-head"><div><span class="eyebrow">CAPABILITY</span><h3>Fitur workspace</h3></div></div><div class="plan-entitlement-grid-v46">${entitlements.filter(e=>e.plan_code===current).map(e=>`<div class="entitlement-card-v46"><span>✓</span><div><strong>${esc(e.capability.replaceAll('_',' '))}</strong><small>${e.limit_value==null?'Tanpa batas':`Limit ${Number(e.limit_value).toLocaleString('id-ID')}`}</small></div></div>`).join('')||'<p class="muted">Belum ada entitlement untuk paket ini.</p>'}</div></section><section class="panel-card"><div class="panel-head"><div><span class="eyebrow">BILLING</span><h3>Paket aktif</h3></div></div><div class="billing-card-v46"><div><span>Harga</span><strong>${Number(meta?.monthly_price||0)===0?'Gratis':`Rp ${Number(meta.monthly_price).toLocaleString('id-ID')} / bulan`}</strong></div><div><span>Status</span><strong>${active?'Aktif':'Belum aktif'}</strong></div><div><span>Upgrade</span><strong>WhatsApp + bukti transfer</strong></div></div></section>`;
    document.getElementById('change-plan').onclick=()=>renderPlanChoice(document.getElementById('organizer-content'),orgId);
  }
    window.SYKA_PAGE_ORGANIZER={render};
})();
