(function(){
  function escape(v){return window.SYKA_UTILS.escapeHtml(v);}
  async function render(root){
    const auth=window.SYKA_STATE.getState().auth;
    if(!auth.user){root.innerHTML=`<div class="auth-gate"><div><h1>Profil Saya</h1><p>Masuk untuk mengelola profil dan rekam prestasi.</p><button class="btn btn-primary" id="profile-login">Masuk</button></div></div>`;document.getElementById('profile-login').onclick=()=>window.SYKA_APP.openAuth('login',{target:'/profile'});return;}
    const p=auth.profile||{};const name=p.full_name||auth.user.email?.split('@')[0]||'Pengguna';const avatar=p.avatar_url||'';
    root.innerHTML=`<div class="section-head page-title"><div><span class="eyebrow">ACCOUNT</span><h1>Profil Saya</h1><p>Kelola data identitas, sekolah, dan foto profil.</p></div></div><div class="profile-layout"><aside class="syka-card profile-card"><div class="profile-avatar" id="profile-avatar">${avatar?`<img src="${escape(avatar)}" alt="">`:escape(window.SYKA_UTILS.initials(name))}</div><h1>${escape(name)}</h1><p>${escape(p.username?`@${p.username}`:auth.user.email||'')}</p><button class="btn btn-primary btn-block" id="change-avatar">Ubah foto profil</button><small class="profile-help">Maks. 5 MB · JPG/PNG/WebP</small></aside><section class="profile-main"><form id="profile-form" class="syka-card form-card"><div class="form-grid-2"><label>Nama lengkap<input id="pf-name" required value="${escape(p.full_name||'')}"></label><label>Username<input id="pf-username" required value="${escape(p.username||'')}"></label></div><div class="form-grid-2"><label>Tanggal lahir<input id="pf-birth" type="date" required value="${escape(p.birth_date||'')}"></label><label>Kelas<select id="pf-grade" required></select></label></div><div class="form-grid-2"><label>Sekolah<input id="pf-school" required value="${escape(p.institution||'')}" placeholder="Mulai ketik nama sekolah"></label><label>Pembina / guru pendamping<input id="pf-guardian" value="${escape(p.guardian_name||'')}"></label></div><div id="school-suggest" class="suggest-list hidden"></div><label>Bio<textarea id="pf-bio">${escape(p.bio||'')}</textarea></label><div class="form-actions"><button class="btn btn-primary">Simpan perubahan</button></div><div id="profile-feedback"></div></form></section></div>`;
    const grade=document.getElementById('pf-grade'); grade.innerHTML=['SD6','SMP1','SMP2','SMP3','SMA1','SMA2','SMA3'].map(x=>`<option value="${x}">${x.replace('SD','Kelas ').replace('SMP','Kelas ').replace('SMA','Kelas ')}</option>`).join(''); grade.value=p.grade||'SD6';
    document.getElementById('change-avatar').onclick=()=>window.SYKA_CLOUDINARY.openAvatarWidget(async info=>{try{const payload={avatar_url:info.secure_url,avatar_public_id:info.public_id,avatar_width:info.width||null,avatar_height:info.height||null,avatar_version:info.version?String(info.version):null,avatar_resource_type:info.resource_type||'image'};const updated=await window.SYKA_PROFILE_SERVICE.updateProfile(auth.user.id,payload);window.SYKA_STATE.patch('auth.profile',updated);window.SYKA_HEADER.render();window.SYKA_SIDEBAR.render();document.getElementById('profile-avatar').innerHTML=`<img src="${escape(updated.avatar_url)}" alt="">`;window.SYKA_TOAST.show('Foto profil berhasil diperbarui.','success');}catch(e){window.SYKA_TOAST.show(e.message||'Upload foto gagal.','error');}},e=>window.SYKA_TOAST.show(e.message||'Upload foto gagal.','error'));
    const schoolInput=document.getElementById('pf-school'),suggest=document.getElementById('school-suggest');let timer;let selectedSchoolId=p.school_id||null; schoolInput.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=schoolInput.value.trim();if(q.length<2){suggest.classList.add('hidden');return;}try{const rows=await window.SYKA_ADMIN_SERVICE.searchSchools(q);suggest.innerHTML=rows.map(s=>`<button type="button" data-id="${escape(s.id)}" data-name="${escape(s.name)}">${escape(s.name)}${s.city?`<small>${escape(s.city)}</small>`:''}</button>`).join('');suggest.classList.toggle('hidden',!rows.length);suggest.querySelectorAll('button').forEach(b=>b.onclick=()=>{schoolInput.value=b.dataset.name;selectedSchoolId=b.dataset.id||null;suggest.classList.add('hidden');});}catch(_){suggest.classList.add('hidden');}},250);});
    document.getElementById('profile-form').onsubmit=async e=>{e.preventDefault();const feedback=document.getElementById('profile-feedback');const payload={full_name:document.getElementById('pf-name').value.trim(),username:document.getElementById('pf-username').value.trim().toLowerCase(),birth_date:document.getElementById('pf-birth').value||null,grade:document.getElementById('pf-grade').value,institution:document.getElementById('pf-school').value.trim(),school_id:selectedSchoolId,guardian_name:document.getElementById('pf-guardian').value.trim()||null,bio:document.getElementById('pf-bio').value.trim()||null};try{const updated=await window.SYKA_PROFILE_SERVICE.updateProfile(auth.user.id,payload);window.SYKA_STATE.patch('auth.profile',updated);window.SYKA_HEADER.render();feedback.innerHTML='<div class="state-banner success">Profil berhasil disimpan.</div>';}catch(err){feedback.innerHTML=`<div class="inline-error">${escape(err.message||'Gagal menyimpan profil.')}</div>`;}};
  }
  window.SYKA_PAGE_PROFILE={render};
})();
