(function(){
  const classes=[['SD6','Kelas 6 SD'],['SMP1','Kelas 1 SMP / MTs'],['SMP2','Kelas 2 SMP / MTs'],['SMP3','Kelas 3 SMP / MTs'],['SMA1','Kelas 1 SMA / MA / SMK'],['SMA2','Kelas 2 SMA / MA / SMK'],['SMA3','Kelas 3 SMA / MA / SMK']];
  function options(selected){return classes.map(([v,l])=>`<option value="${v}" ${selected===v?'selected':''}>${l}</option>`).join('');}
  async function render(root,slug){
    const c=await window.SYKA_COMPETITION_SERVICE.getBySlug(slug); if(!c){root.innerHTML=window.SYKA_EMPTY.render({title:'Kompetisi tidak ditemukan',text:'Periksa kembali slug kompetisi.'});return;}
    const auth=window.SYKA_STATE.getState().auth;
    if(!auth.user){root.innerHTML=`<div class="auth-gate"><div><h1>Daftar kompetisi</h1><p>Kamu perlu memiliki akun Sykabelajar sebelum mendaftar.</p><button class="btn btn-primary" id="reg-login">Masuk / Daftar</button></div></div>`;document.getElementById('reg-login').onclick=()=>window.SYKA_APP.openAuth('register',{target:window.SYKA_UTILS.routePath()});return;}
    const p=auth.profile||{};
    root.innerHTML=`<div class="form-page"><div class="form-intro"><span class="eyebrow">REGISTRATION</span><h1>Daftar ${window.SYKA_UTILS.escapeHtml(c.title)}</h1><p>Lengkapi data peserta. Data akun utama digunakan untuk seluruh proses kompetisi dan rekam prestasi.</p></div><form id="competition-registration-form" class="syka-card form-card"><div class="form-grid-2"><label>Nama lengkap *<input id="rg-name" required value="${window.SYKA_UTILS.escapeHtml(p.full_name||'')}"></label><label>Username *<input id="rg-username" required value="${window.SYKA_UTILS.escapeHtml(p.username||'')}"></label></div><div class="form-grid-2"><label>Email *<input id="rg-email" type="email" required value="${window.SYKA_UTILS.escapeHtml(auth.user.email||'')}" readonly></label><div class="state-banner">Password dikelola melalui akun Sykabelajar dan tidak perlu dimasukkan ulang saat mendaftar lomba.</div></div><div class="form-grid-2"><label>Tanggal lahir *<input id="rg-birth" type="date" required value="${window.SYKA_UTILS.escapeHtml(p.birth_date||'')}"></label><label>Kelas *<select id="rg-grade" required>${options(p.grade||'')}</select></label></div><div class="form-grid-2"><label>Sekolah *<input id="rg-school" required value="${window.SYKA_UTILS.escapeHtml(p.institution||'')}" placeholder="Mulai ketik nama sekolah"></label><label>Pembina / guru pendamping <input id="rg-guardian" value="${window.SYKA_UTILS.escapeHtml(p.guardian_name||'')}"></label></div><div id="rg-school-suggest" class="suggest-list hidden"></div><div class="state-banner">Nama sekolah akan disimpan dalam format kapital/uppercase. Jika ditemukan sekolah yang mirip, pilih rekomendasi agar data sekolah lebih konsisten.</div><div class="form-actions"><a class="btn btn-ghost" href="${window.SYKA_ROUTER.href('/lomba/'+encodeURIComponent(slug))}">Kembali</a><button class="btn btn-primary">Daftar sekarang</button></div><div id="rg-feedback"></div></form></div>`;
    const school=document.getElementById('rg-school'),suggest=document.getElementById('rg-school-suggest'); let timer; let selectedSchoolId=p.school_id||null;school.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=school.value.trim();if(q.length<2){suggest.classList.add('hidden');return;}try{const rows=await window.SYKA_ADMIN_SERVICE.searchSchools(q);suggest.innerHTML=rows.map(s=>`<button type="button" data-id="${window.SYKA_UTILS.escapeHtml(s.id)}" data-name="${window.SYKA_UTILS.escapeHtml(s.name)}">${window.SYKA_UTILS.escapeHtml(s.name)}${s.city?`<small>${window.SYKA_UTILS.escapeHtml(s.city)}</small>`:''}</button>`).join('');suggest.classList.toggle('hidden',!rows.length);suggest.querySelectorAll('button').forEach(b=>b.onclick=()=>{school.value=b.dataset.name;selectedSchoolId=b.dataset.id||null;suggest.classList.add('hidden');});}catch(_){suggest.classList.add('hidden');}},250);});
    document.getElementById('competition-registration-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,feedback=document.getElementById('rg-feedback');const payload={full_name:f.querySelector('#rg-name').value.trim(),username:f.querySelector('#rg-username').value.trim().toLowerCase(),birth_date:f.querySelector('#rg-birth').value||null,grade:f.querySelector('#rg-grade').value,institution:f.querySelector('#rg-school').value.trim().toUpperCase(),school_id:selectedSchoolId,guardian_name:f.querySelector('#rg-guardian').value.trim()||null};try{const updated=await window.SYKA_PROFILE_SERVICE.updateProfile(auth.user.id,payload);window.SYKA_STATE.patch('auth.profile',updated);const reg=await window.SYKA_REGISTRATION_SERVICE.register({competitionId:c.id});feedback.innerHTML='<div class="state-banner success">Data peserta tersimpan dan pendaftaran berhasil dikirim.</div>';f.querySelector('button.btn-primary').disabled=true;window.SYKA_TOAST.show('Pendaftaran berhasil dikirim.','success');return reg;}catch(err){feedback.innerHTML=`<div class="inline-error">${window.SYKA_UTILS.escapeHtml(err.message||'Pendaftaran gagal.')}</div>`;}};
  }
  window.SYKA_PAGE_REGISTRATION={render};
})();
