(function(){
  const esc=v=>window.SYKA_UTILS.escapeHtml(v); const fmt=v=>window.SYKA_UTILS.formatDateTime(v);
  async function render(root){
    const auth=window.SYKA_STATE.getState().auth;
    if(!auth.user){root.innerHTML=window.SYKA_EMPTY.render({title:'Masuk diperlukan',text:'Masuk untuk melihat misi harian dan reward.',actionHtml:'<button class="btn btn-primary" id="task-login">Masuk</button>'});root.querySelector('#task-login')?.addEventListener('click',()=>window.SYKA_APP.openAuth('login',{target:'/tugas'}));return;}
    let tasks=[]; try{tasks=await window.SYKA_TASK_SERVICE.listTasks();}catch(e){root.innerHTML=window.SYKA_EMPTY.render({title:'Tugas belum tersedia',text:e.message||'Modul task belum tersambung.'});return;}
    root.innerHTML=`<section class="page-title"><span class="eyebrow">DAILY TASK</span><h1>Misi & reward</h1><p>Selesaikan aktivitas ringan untuk mendapatkan Koin Edu dan EXP. Progress dan reward diselesaikan oleh server.</p></section><div class="task-grid-v410">${tasks.map(t=>`<article class="task-card-v410" data-task-card="${t.id}"><div class="task-icon-v410">✦</div><div class="task-body-v410"><div class="task-meta-v410"><span>${esc(t.task_type||'TASK')}</span><span>+${Number(t.points||0)} Koin</span><span>+${Number(t.exp||0)} EXP</span></div><h2>${esc(t.title)}</h2><p>${esc(t.description||'Selesaikan misi ini untuk mendapat reward.')}</p><div class="task-actions-v410"><button class="btn btn-primary btn-sm" data-task-claim="${t.id}">Mulai misi</button><button class="btn btn-secondary btn-sm hidden" data-task-complete="${t.id}">Tandai selesai</button></div></div></article>`).join('')||window.SYKA_EMPTY.render({title:'Belum ada misi',text:'Misi akan muncul saat Admin mengaktifkannya.'})}</div>`;
    root.querySelectorAll('[data-task-claim]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await window.SYKA_TASK_SERVICE.claim(btn.dataset.taskClaim);btn.classList.add('hidden');const complete=btn.closest('[data-task-card]')?.querySelector('[data-task-complete]');complete?.classList.remove('hidden');window.SYKA_TOAST.show('Misi dimulai. Selesaikan aktivitasnya lalu tandai selesai.','success');}catch(e){btn.disabled=false;window.SYKA_TOAST.show(e.message||'Misi gagal dibuka.','error');}});
    root.querySelectorAll('[data-task-complete]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{const r=await window.SYKA_TASK_SERVICE.complete(btn.dataset.taskComplete);btn.textContent='Selesai';window.SYKA_TOAST.show(r?.already?'Misi ini sudah selesai.':`Reward diterima: +${Number(r?.points||0)} Koin Edu · +${Number(r?.exp||0)} EXP.`,'success');}catch(e){btn.disabled=false;window.SYKA_TOAST.show(e.message||'Misi belum dapat diselesaikan.','error');}});
  }
  window.SYKA_PAGE_TASKS={render};
})();