(function(){
  function render(){
    const auth=window.SYKA_STATE.getState().auth;
    const u=auth.user; const p=auth.profile||{};
    const name=p.full_name||p.name||u?.user_metadata?.full_name||u?.email?.split('@')[0]||'Pengguna';
    const avatar=p.avatar_url||u?.user_metadata?.avatar_url||''; const initial=window.SYKA_UTILS.initials(name);
    const isAdmin=auth.roles.includes('admin'); const isOrganizer=auth.roles.includes('organizer_member');
    document.getElementById('syka-header').innerHTML=`<div class="header-left"><button class="mobile-menu" id="mobile-menu-btn" aria-label="Menu">☰</button></div><div class="header-center"><div class="announcement"><span class="announcement-icon">◉</span><span>Kompetisi, prestasi, dan pengalaman belajar dalam satu tempat.</span></div></div><div class="header-right"><button class="theme-btn" id="theme-btn" title="Ganti tema">◐</button>${u?`<div class="profile-quick"><button id="profile-quick-btn" class="profile-trigger">${avatar?`<img src="${window.SYKA_UTILS.escapeHtml(avatar)}" alt="">`:`<span>${initial}</span>`}<span class="profile-name-role"><b>${window.SYKA_UTILS.escapeHtml(name)}</b><small>${window.SYKA_UTILS.escapeHtml(auth.roles[0]||'Pelajar')}</small></span></button><div id="profile-menu" class="profile-menu hidden">${isAdmin?`<a href="${window.SYKA_ROUTER.href('/admin')}">Panel Admin</a>`:''}${isOrganizer||isAdmin?`<a href="${window.SYKA_ROUTER.href('/organizer')}">Panel Penyelenggara</a>`:''}<a href="${window.SYKA_ROUTER.href('/profile')}">Profil Saya</a><a href="${window.SYKA_ROUTER.href('/prestasi')}">Prestasi</a><a href="${window.SYKA_ROUTER.href('/pesanan')}">Pesanan</a><button id="logout-btn">Keluar</button></div></div>`:`<button class="btn btn-primary btn-sm" id="header-login">Masuk</button>`}</div>`; bind(); }
  function bind(){ document.getElementById('theme-btn')?.addEventListener('click',()=>window.SYKA_APP.toggleTheme()); document.getElementById('mobile-menu-btn')?.addEventListener('click',()=>window.SYKA_APP.toggleMobileNav()); document.getElementById('header-login')?.addEventListener('click',()=>window.SYKA_APP.openAuth('login')); const t=document.getElementById('profile-quick-btn'); const m=document.getElementById('profile-menu'); if(t&&m){t.onclick=e=>{e.stopPropagation();m.classList.toggle('hidden');}; if(!window.__SYKA_PROFILE_MENU_BOUND){window.__SYKA_PROFILE_MENU_BOUND=true;document.addEventListener('click',e=>{if(!e.target.closest('.profile-quick'))document.getElementById('profile-menu')?.classList.add('hidden');});}} document.getElementById('logout-btn')?.addEventListener('click',()=>window.SYKA_APP.logout()); }
  window.SYKA_HEADER={render};
})();
