(function(){
  function roleLabel(roles){if(roles.includes('admin'))return 'Admin';if(roles.includes('organizer_member'))return 'Penyelenggara';if(roles.includes('teacher'))return 'Guru';return 'Pelajar';}
  function render(){const auth=window.SYKA_STATE.getState().auth;const u=auth.user,p=auth.profile||{};const name=p.full_name||u?.user_metadata?.full_name||u?.email?.split('@')[0]||'Pengguna';const avatar=p.avatar_url||'';const canAdmin=auth.roles.includes('admin');const canOrganizer=auth.roles.includes('organizer_member')||canAdmin;const icon=auth.status==='authenticated'?'✓':'•';
    const el=document.getElementById('syka-header');if(!el)return;
    el.innerHTML=`<div class="header-inner"><div class="header-mobile-left"><button class="icon-btn mobile-menu" id="mobile-menu-btn" aria-label="Menu">☰</button></div><div class="header-announcement"><span class="announcement-dot">${icon}</span><span>Kompetisi, prestasi, dan pengalaman belajar dalam satu tempat.</span></div><div class="header-actions"><button class="icon-btn" id="theme-btn" title="Ganti tema">${document.documentElement.dataset.theme==='dark'?'☀':'◐'}</button>${u?`<div class="profile-quick"><button class="profile-trigger" id="profile-quick-btn"><span class="profile-avatar-mini">${avatar?`<img src="${window.SYKA_UTILS.escapeHtml(avatar)}" alt="">`:`${window.SYKA_UTILS.initials(name)}`}</span><span class="profile-text"><strong>${window.SYKA_UTILS.escapeHtml(name)}</strong><small>${roleLabel(auth.roles)}</small></span><span class="profile-chevron">⌄</span></button><div class="profile-menu hidden" id="profile-menu">${canAdmin?`<button data-go="/admin">Panel Admin</button>`:''}${canOrganizer?`<button data-go="/organizer">Panel Penyelenggara</button>`:''}<button data-go="/profile">Profil Saya</button><button data-go="/prestasi">Prestasi</button><button data-go="/pesanan">Pesanan</button><button class="danger" id="logout-btn">Keluar</button></div></div>`:`<button class="btn btn-primary btn-sm" id="header-login">Masuk</button>`}</div></div>`;
    document.getElementById('theme-btn')?.addEventListener('click',()=>window.SYKA_APP.toggleTheme());document.getElementById('mobile-menu-btn')?.addEventListener('click',()=>window.SYKA_APP.toggleMobileNav());document.getElementById('header-login')?.addEventListener('click',()=>window.SYKA_APP.openAuth('login'));
    const trigger=document.getElementById('profile-quick-btn'),menu=document.getElementById('profile-menu');if(trigger&&menu)trigger.onclick=e=>{e.stopPropagation();menu.classList.toggle('hidden');};menu?.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{menu.classList.add('hidden');window.SYKA_ROUTER.navigate(b.dataset.go);});document.getElementById('logout-btn')?.addEventListener('click',()=>window.SYKA_APP.logout());
  }
  window.SYKA_HEADER={render};
})();
